export const CITIES_BY_STATE: Record<string, string[]> = {
  Alabama: [
    "Alabaster",
    "Albertville",
    "Anniston",
    "Athens",
    "Auburn",
    "Bessemer",
    "Birmingham",
    "Daphne",
    "Decatur",
    "Dothan",
    "Enterprise",
    "Fairhope",
    "Florence",
    "Gadsden",
    "Homewood",
    "Hoover",
    "Huntsville",
    "Madison",
    "Mobile",
    "Montgomery",
    "Northport",
    "Opelika",
    "Oxford",
    "Pelham",
    "Phenix City",
    "Prattville",
    "Prichard",
    "Trussville",
    "Tuscaloosa",
    "Vestavia Hills",
  ],
  Alaska: [
    "Akutan",
    "Anchorage",
    "Bethel",
    "Chevak",
    "Cordova",
    "Craig",
    "Delta Junction",
    "Dillingham",
    "Fairbanks",
    "Homer",
    "Hooper Bay",
    "Houston",
    "Juneau",
    "Kenai",
    "Ketchikan",
    "King Cove",
    "Kodiak",
    "Kotzebue",
    "Nome",
    "North Pole",
    "Palmer",
    "Sand Point",
    "Seward",
    "Sitka",
    "Soldotna",
    "Unalaska",
    "Utqiagvik",
    "Valdez",
    "Wasilla",
    "Wrangell",
  ],
  Arizona: [
    "Apache Junction",
    "Avondale",
    "Buckeye",
    "Bullhead City",
    "Casa Grande",
    "Chandler",
    "El Mirage",
    "Flagstaff",
    "Gilbert",
    "Glendale",
    "Goodyear",
    "Kingman",
    "Lake Havasu City",
    "Marana",
    "Maricopa",
    "Mesa",
    "Oro Valley",
    "Peoria",
    "Phoenix",
    "Prescott",
    "Prescott Valley",
    "Queen Creek",
    "Sahuarita",
    "San Luis",
    "Scottsdale",
    "Sierra Vista",
    "Surprise",
    "Tempe",
    "Tucson",
    "Yuma",
  ],
  Arkansas: [
    "Bella Vista",
    "Benton",
    "Bentonville",
    "Blytheville",
    "Bryant",
    "Cabot",
    "Centerton",
    "Conway",
    "El Dorado",
    "Fayetteville",
    "Forrest City",
    "Fort Smith",
    "Harrison",
    "Hot Springs",
    "Jacksonville",
    "Jonesboro",
    "Little Rock",
    "Maumelle",
    "North Little Rock",
    "Paragould",
    "Pine Bluff",
    "Rogers",
    "Russellville",
    "Searcy",
    "Sherwood",
    "Siloam Springs",
    "Springdale",
    "Texarkana",
    "Van Buren",
    "West Memphis",
  ],
  California: [
    "Anaheim",
    "Bakersfield",
    "Chula Vista",
    "Elk Grove",
    "Fontana",
    "Fremont",
    "Fresno",
    "Garden Grove",
    "Glendale",
    "Huntington Beach",
    "Irvine",
    "Long Beach",
    "Los Angeles",
    "Modesto",
    "Moreno Valley",
    "Oakland",
    "Oceanside",
    "Ontario",
    "Oxnard",
    "Rancho Cucamonga",
    "Riverside",
    "Sacramento",
    "San Bernardino",
    "San Diego",
    "San Francisco",
    "San Jose",
    "Santa Ana",
    "Santa Clarita",
    "Santa Rosa",
    "Stockton",
  ],
  Colorado: [
    "Arvada",
    "Aurora",
    "Boulder",
    "Brighton",
    "Broomfield",
    "Castle Rock",
    "Centennial",
    "Colorado Springs",
    "Commerce City",
    "Denver",
    "Englewood",
    "Erie",
    "Evans",
    "Fort Collins",
    "Fountain",
    "Grand Junction",
    "Greeley",
    "Lafayette",
    "Lakewood",
    "Littleton",
    "Longmont",
    "Louisville",
    "Loveland",
    "Northglenn",
    "Parker",
    "Pueblo",
    "Thornton",
    "Westminster",
    "Wheat Ridge",
    "Windsor",
  ],
  Connecticut: [
    "Ansonia",
    "Bantam",
    "Bridgeport",
    "Bristol",
    "Danbury",
    "Danielson",
    "Derby",
    "Fenwick",
    "Groton",
    "Groton Long Point",
    "Hartford",
    "Jewett City",
    "Litchfield",
    "Meriden",
    "Middletown",
    "Milford",
    "Naugatuck",
    "New Britain",
    "New Haven",
    "New London",
    "Newtown",
    "Norwalk",
    "Norwich",
    "Shelton",
    "Stamford",
    "Stonington",
    "Torrington",
    "Waterbury",
    "West Haven",
    "Woodmont",
  ],
  Delaware: [
    "Bellefonte",
    "Bethany Beach",
    "Blades",
    "Bridgeville",
    "Camden",
    "Cheswold",
    "Clayton",
    "Delaware City",
    "Delmar",
    "Dover",
    "Elsmere",
    "Felton",
    "Georgetown",
    "Harrington",
    "Laurel",
    "Lewes",
    "Middletown",
    "Milford",
    "Millsboro",
    "Milton",
    "New Castle",
    "Newark",
    "Ocean View",
    "Rehoboth Beach",
    "Seaford",
    "Selbyville",
    "Smyrna",
    "Townsend",
    "Wilmington",
    "Wyoming",
  ],
  "District of Columbia": [
    "Washington",
  ],
  Florida: [
    "Boca Raton",
    "Cape Coral",
    "Clearwater",
    "Coral Springs",
    "Davie",
    "Deltona",
    "Fort Lauderdale",
    "Fort Myers",
    "Gainesville",
    "Hialeah",
    "Hollywood",
    "Jacksonville",
    "Lakeland",
    "Largo",
    "Miami",
    "Miami Beach",
    "Miami Gardens",
    "Miramar",
    "Orlando",
    "Palm Bay",
    "Palm Coast",
    "Pembroke Pines",
    "Plantation",
    "Pompano Beach",
    "Port St. Lucie",
    "St. Petersburg",
    "Sunrise",
    "Tallahassee",
    "Tampa",
    "West Palm Beach",
  ],
  Georgia: [
    "Albany",
    "Alpharetta",
    "Athens-clarke County Unified Government (balance)",
    "Atlanta",
    "Augusta",
    "Brookhaven",
    "Columbus",
    "Dalton",
    "Douglasville",
    "Dunwoody",
    "East Point",
    "Gainesville",
    "Johns Creek",
    "Kennesaw",
    "Macon",
    "Marietta",
    "Milton",
    "Newnan",
    "Peachtree City",
    "Peachtree Corners",
    "Rome",
    "Roswell",
    "Sandy Springs",
    "Savannah",
    "Smyrna",
    "South Fulton",
    "Stonecrest",
    "Tucker",
    "Valdosta",
    "Warner Robins",
  ],
  Hawaii: [
    "Honolulu",
  ],
  Idaho: [
    "Ammon",
    "Blackfoot",
    "Boise",
    "Burley",
    "Caldwell",
    "Chubbuck",
    "Coeur d'Alene",
    "Eagle",
    "Emmett",
    "Garden City",
    "Hailey",
    "Hayden",
    "Idaho Falls",
    "Jerome",
    "Kuna",
    "Lewiston",
    "Meridian",
    "Middleton",
    "Moscow",
    "Mountain Home",
    "Nampa",
    "Payette",
    "Pocatello",
    "Post Falls",
    "Rathdrum",
    "Rexburg",
    "Rupert",
    "Sandpoint",
    "Star",
    "Twin Falls",
  ],
  Illinois: [
    "Arlington Heights",
    "Aurora",
    "Berwyn",
    "Bloomington",
    "Bolingbrook",
    "Champaign",
    "Chicago",
    "Cicero",
    "Decatur",
    "Des Plaines",
    "Downers Grove",
    "Elgin",
    "Evanston",
    "Hoffman Estates",
    "Joliet",
    "Mount Prospect",
    "Naperville",
    "Normal",
    "Oak Lawn",
    "Oak Park",
    "Orland Park",
    "Palatine",
    "Peoria",
    "Rockford",
    "Schaumburg",
    "Skokie",
    "Springfield",
    "Tinley Park",
    "Waukegan",
    "Wheaton",
  ],
  Indiana: [
    "Anderson",
    "Bloomington",
    "Carmel",
    "Columbus",
    "Elkhart",
    "Evansville",
    "Fishers",
    "Fort Wayne",
    "Gary",
    "Goshen",
    "Greenwood",
    "Hammond",
    "Indianapolis",
    "Jeffersonville",
    "Kokomo",
    "Lafayette",
    "Lawrence",
    "Merrillville",
    "Mishawaka",
    "Muncie",
    "New Albany",
    "Noblesville",
    "Plainfield",
    "Portage",
    "Richmond",
    "South Bend",
    "Terre Haute",
    "Valparaiso",
    "West Lafayette",
    "Westfield",
  ],
  Iowa: [
    "Altoona",
    "Ames",
    "Ankeny",
    "Bettendorf",
    "Burlington",
    "Cedar Falls",
    "Cedar Rapids",
    "Clinton",
    "Clive",
    "Coralville",
    "Council Bluffs",
    "Davenport",
    "Des Moines",
    "Dubuque",
    "Fort Dodge",
    "Indianola",
    "Iowa City",
    "Johnston",
    "Marion",
    "Marshalltown",
    "Mason City",
    "Muscatine",
    "Newton",
    "North Liberty",
    "Ottumwa",
    "Sioux City",
    "Urbandale",
    "Waterloo",
    "Waukee",
    "West Des Moines",
  ],
  Kansas: [
    "Andover",
    "Derby",
    "Dodge City",
    "El Dorado",
    "Emporia",
    "Garden City",
    "Gardner",
    "Great Bend",
    "Hays",
    "Hutchinson",
    "Junction City",
    "Kansas City",
    "Lansing",
    "Lawrence",
    "Leavenworth",
    "Leawood",
    "Lenexa",
    "Liberal",
    "Manhattan",
    "Mcpherson",
    "Newton",
    "Olathe",
    "Ottawa",
    "Overland Park",
    "Pittsburg",
    "Prairie",
    "Salina",
    "Shawnee",
    "Topeka",
    "Wichita",
  ],
  Kentucky: [
    "Ashland",
    "Berea",
    "Bowling Green",
    "Covington",
    "Danville",
    "Elizabethtown",
    "Erlanger",
    "Florence",
    "Fort Thomas",
    "Frankfort",
    "Georgetown",
    "Henderson",
    "Hopkinsville",
    "Independence",
    "Jeffersontown",
    "Lexington",
    "Louisville",
    "Madisonville",
    "Mount Washington",
    "Murray",
    "Newport",
    "Nicholasville",
    "Owensboro",
    "Paducah",
    "Radcliff",
    "Richmond",
    "Shelbyville",
    "Shively",
    "St. Matthews",
    "Winchester",
  ],
  Louisiana: [
    "Abbeville",
    "Alexandria",
    "Baker",
    "Baton Rouge",
    "Bossier City",
    "Broussard",
    "Central",
    "Crowley",
    "Gretna",
    "Hammond",
    "Houma",
    "Kenner",
    "Lafayette",
    "Lake Charles",
    "Mandeville",
    "Minden",
    "Monroe",
    "Natchitoches",
    "New Iberia",
    "New Orleans",
    "Opelousas",
    "Pineville",
    "Ruston",
    "Shreveport",
    "Slidell",
    "Sulphur",
    "Thibodaux",
    "West Monroe",
    "Youngsville",
    "Zachary",
  ],
  Maine: [
    "Auburn",
    "Augusta",
    "Bangor",
    "Bath",
    "Belfast",
    "Biddeford",
    "Brewer",
    "Calais",
    "Caribou",
    "Eastport",
    "Ellsworth",
    "Gardiner",
    "Hallowell",
    "Lewiston",
    "Old",
    "Portland",
    "Presque Isle",
    "Rockland",
    "Saco",
    "Sanford",
    "South Portland",
    "Waterville",
    "Westbrook",
  ],
  Maryland: [
    "Aberdeen",
    "Annapolis",
    "Baltimore",
    "Bel Air",
    "Bladensburg",
    "Bowie",
    "Cambridge",
    "College Park",
    "Cumberland",
    "Easton",
    "Elkton",
    "Frederick",
    "Frostburg",
    "Gaithersburg",
    "Greenbelt",
    "Hagerstown",
    "Havre De Grace",
    "Hyattsville",
    "La Plata",
    "Laurel",
    "Mount Airy",
    "Mount Rainier",
    "New Carrollton",
    "Ocean City",
    "Riverdale Park",
    "Rockville",
    "Salisbury",
    "Takoma Park",
    "Thurmont",
    "Westminster",
  ],
  Massachusetts: [
    "Attleboro",
    "Barnstable",
    "Beverly",
    "Boston",
    "Brockton",
    "Cambridge",
    "Chicopee",
    "Everett",
    "Fall River",
    "Framingham",
    "Haverhill",
    "Lawrence",
    "Lowell",
    "Lynn",
    "Malden",
    "Medford",
    "Methuen",
    "New Bedford",
    "Newton",
    "Peabody",
    "Pittsfield",
    "Quincy",
    "Revere",
    "Salem",
    "Somerville",
    "Springfield",
    "Taunton",
    "Waltham",
    "Weymouth",
    "Worcester",
  ],
  Michigan: [
    "Ann Arbor",
    "Battle Creek",
    "Dearborn",
    "Dearborn Heights",
    "Detroit",
    "East Lansing",
    "Farmington Hills",
    "Flint",
    "Grand Rapids",
    "Kalamazoo",
    "Kentwood",
    "Lansing",
    "Livonia",
    "Midland",
    "Muskegon",
    "Novi",
    "Pontiac",
    "Portage",
    "Rochester Hills",
    "Roseville",
    "Royal Oak",
    "Saginaw",
    "Southfield",
    "St. Clair Shores",
    "Sterling Heights",
    "Taylor",
    "Troy",
    "Warren",
    "Westland",
    "Wyoming",
  ],
  Minnesota: [
    "Andover",
    "Apple Valley",
    "Blaine",
    "Bloomington",
    "Brooklyn Park",
    "Burnsville",
    "Coon Rapids",
    "Cottage Grove",
    "Duluth",
    "Eagan",
    "Eden Prairie",
    "Edina",
    "Inver Grove Heights",
    "Lakeville",
    "Mankato",
    "Maple Grove",
    "Maplewood",
    "Minneapolis",
    "Minnetonka",
    "Moorhead",
    "Plymouth",
    "Richfield",
    "Rochester",
    "Roseville",
    "Savage",
    "Shakopee",
    "St. Cloud",
    "St. Louis Park",
    "St. Paul",
    "Woodbury",
  ],
  Mississippi: [
    "Bay St. Louis",
    "Biloxi",
    "Brandon",
    "Clarksdale",
    "Clinton",
    "Columbus",
    "Corinth",
    "D'iberville",
    "Gautier",
    "Greenville",
    "Gulfport",
    "Hattiesburg",
    "Hernando",
    "Horn Lake",
    "Jackson",
    "Laurel",
    "Long Beach",
    "Madison",
    "Meridian",
    "Natchez",
    "Ocean Springs",
    "Olive Branch",
    "Oxford",
    "Pascagoula",
    "Pearl",
    "Ridgeland",
    "Southaven",
    "Starkville",
    "Tupelo",
    "Vicksburg",
  ],
  Missouri: [
    "Ballwin",
    "Belton",
    "Blue Springs",
    "Cape Girardeau",
    "Chesterfield",
    "Columbia",
    "Florissant",
    "Gladstone",
    "Grandview",
    "Hazelwood",
    "Independence",
    "Jefferson City",
    "Joplin",
    "Kansas City",
    "Kirkwood",
    "Lee's Summit",
    "Liberty",
    "Maryland Heights",
    "Nixa",
    "O'fallon",
    "Raytown",
    "Springfield",
    "St. Charles",
    "St. Joseph",
    "St. Louis",
    "St. Peters",
    "University City",
    "Webster Groves",
    "Wentzville",
    "Wildwood",
  ],
  Montana: [
    "Anaconda-deer Lodge",
    "Belgrade",
    "Billings",
    "Bozeman",
    "Butte",
    "Columbia Falls",
    "Conrad",
    "Cut Bank",
    "Deer Lodge",
    "Dillon",
    "Glasgow",
    "Glendive",
    "Great Falls",
    "Hamilton",
    "Hardin",
    "Havre",
    "Helena",
    "Kalispell",
    "Laurel",
    "Lewistown",
    "Libby",
    "Livingston",
    "Miles City",
    "Missoula",
    "Polson",
    "Red Lodge",
    "Shelby",
    "Sidney",
    "Whitefish",
    "Wolf Point",
  ],
  Nebraska: [
    "Alliance",
    "Beatrice",
    "Bellevue",
    "Blair",
    "Chadron",
    "Columbus",
    "Crete",
    "Fremont",
    "Gering",
    "Grand Island",
    "Hastings",
    "Kearney",
    "La Vista",
    "Lexington",
    "Lincoln",
    "Mccook",
    "Nebraska City",
    "Norfolk",
    "North Platte",
    "Omaha",
    "Papillion",
    "Plattsmouth",
    "Ralston",
    "Schuyler",
    "Scottsbluff",
    "Seward",
    "Sidney",
    "South Sioux City",
    "Wayne",
    "York",
  ],
  Nevada: [
    "Boulder City",
    "Caliente",
    "Carlin",
    "Carson",
    "Elko",
    "Ely",
    "Fallon",
    "Fernley",
    "Henderson",
    "Las Vegas",
    "Lovelock",
    "Mesquite",
    "North Las Vegas",
    "Reno",
    "Sparks",
    "Wells",
    "West Wendover",
    "Winnemucca",
    "Yerington",
  ],
  "New Hampshire": [
    "Berlin",
    "Claremont",
    "Concord",
    "Dover",
    "Franklin",
    "Keene",
    "Laconia",
    "Lebanon",
    "Manchester",
    "Nashua",
    "Portsmouth",
    "Rochester",
    "Somersworth",
  ],
  "New Jersey": [
    "Atlantic City",
    "Bayonne",
    "Camden",
    "Clifton",
    "East Orange",
    "Elizabeth",
    "Englewood",
    "Fair Lawn",
    "Fort Lee",
    "Garfield",
    "Hackensack",
    "Hoboken",
    "Jersey City",
    "Kearny",
    "Linden",
    "Long Branch",
    "New Brunswick",
    "Newark",
    "Passaic",
    "Paterson",
    "Perth Amboy",
    "Plainfield",
    "Princeton",
    "Rahway",
    "Sayreville",
    "Trenton",
    "Union City",
    "Vineland",
    "West New York",
    "Westfield",
  ],
  "New Mexico": [
    "Alamogordo",
    "Albuquerque",
    "Anthony",
    "Artesia",
    "Aztec",
    "Belen",
    "Bernalillo",
    "Bloomfield",
    "Carlsbad",
    "Clovis",
    "Corrales",
    "Deming",
    "Española",
    "Farmington",
    "Gallup",
    "Grants",
    "Hobbs",
    "Las Cruces",
    "Las Vegas",
    "Los Lunas",
    "Los Ranchos De Albuquerque",
    "Lovington",
    "Portales",
    "Rio Rancho",
    "Roswell",
    "Ruidoso",
    "Santa Fe",
    "Silver City",
    "Socorro",
    "Sunland Park",
  ],
  "New York": [
    "Albany",
    "Binghamton",
    "Buffalo",
    "Freeport",
    "Glen Cove",
    "Harrison",
    "Hempstead",
    "Ithaca",
    "Jamestown",
    "Long Beach",
    "Middletown",
    "Mount Vernon",
    "New Rochelle",
    "New York City",
    "Newburgh",
    "Niagara Falls",
    "North Tonawanda",
    "Port Chester",
    "Poughkeepsie",
    "Rochester",
    "Rome",
    "Saratoga Springs",
    "Schenectady",
    "Spring Valley",
    "Syracuse",
    "Troy",
    "Utica",
    "Valley Stream",
    "White Plains",
    "Yonkers",
  ],
  "North Carolina": [
    "Apex",
    "Asheville",
    "Burlington",
    "Cary",
    "Chapel Hill",
    "Charlotte",
    "Concord",
    "Durham",
    "Fayetteville",
    "Gastonia",
    "Goldsboro",
    "Greensboro",
    "Greenville",
    "Hickory",
    "High Point",
    "Holly Springs",
    "Huntersville",
    "Indian Trail",
    "Jacksonville",
    "Kannapolis",
    "Matthews",
    "Monroe",
    "Mooresville",
    "Raleigh",
    "Rocky Mount",
    "Salisbury",
    "Wake Forest",
    "Wilmington",
    "Wilson",
    "Winston-Salem",
  ],
  "North Dakota": [
    "Beulah",
    "Bismarck",
    "Bottineau",
    "Carrington",
    "Casselton",
    "Devils Lake",
    "Dickinson",
    "Fargo",
    "Grafton",
    "Grand Forks",
    "Harvey",
    "Hazen",
    "Hillsboro",
    "Horace",
    "Jamestown",
    "Langdon",
    "Lincoln",
    "Lisbon",
    "Mandan",
    "Mayville",
    "Minot",
    "New",
    "Oakes",
    "Rugby",
    "Stanley",
    "Valley City",
    "Wahpeton",
    "Watford City",
    "West Fargo",
    "Williston",
  ],
  Ohio: [
    "Akron",
    "Beavercreek",
    "Canton",
    "Cincinnati",
    "Cleveland",
    "Cleveland Heights",
    "Columbus",
    "Cuyahoga Falls",
    "Dayton",
    "Delaware",
    "Dublin",
    "Elyria",
    "Euclid",
    "Fairfield",
    "Findlay",
    "Grove City",
    "Hamilton",
    "Kettering",
    "Lakewood",
    "Lorain",
    "Mansfield",
    "Mentor",
    "Middletown",
    "Newark",
    "Parma",
    "Springfield",
    "Strongsville",
    "Toledo",
    "Westerville",
    "Youngstown",
  ],
  Oklahoma: [
    "Altus",
    "Ardmore",
    "Bartlesville",
    "Bethany",
    "Bixby",
    "Broken Arrow",
    "Claremore",
    "Del City",
    "Duncan",
    "Durant",
    "Edmond",
    "El Reno",
    "Enid",
    "Jenks",
    "Lawton",
    "Mcalester",
    "Midwest City",
    "Moore",
    "Muskogee",
    "Mustang",
    "Norman",
    "Oklahoma City",
    "Owasso",
    "Ponca City",
    "Sand Springs",
    "Sapulpa",
    "Shawnee",
    "Stillwater",
    "Tulsa",
    "Yukon",
  ],
  Oregon: [
    "Albany",
    "Ashland",
    "Beaverton",
    "Bend",
    "Corvallis",
    "Eugene",
    "Forest Grove",
    "Grants Pass",
    "Gresham",
    "Happy Valley",
    "Hillsboro",
    "Keizer",
    "Klamath Falls",
    "Lake Oswego",
    "Mcminnville",
    "Medford",
    "Milwaukie",
    "Newberg",
    "Oregon City",
    "Portland",
    "Redmond",
    "Roseburg",
    "Salem",
    "Sherwood",
    "Springfield",
    "Tigard",
    "Tualatin",
    "West Linn",
    "Wilsonville",
    "Woodburn",
  ],
  Pennsylvania: [
    "Allentown",
    "Altoona",
    "Baldwin",
    "Bethel Park",
    "Bethlehem",
    "Carlisle",
    "Chambersburg",
    "Chester",
    "Easton",
    "Erie",
    "Harrisburg",
    "Hazleton",
    "Lancaster",
    "Lebanon",
    "Monroeville",
    "Murrysville",
    "New Castle",
    "Norristown",
    "Philadelphia",
    "Pittsburgh",
    "Plum",
    "Pottstown",
    "Reading",
    "Scranton",
    "State College",
    "West Chester",
    "West Mifflin",
    "Wilkes-barre",
    "Williamsport",
    "York",
  ],
  "Rhode Island": [
    "Central Falls",
    "Cranston",
    "East Providence",
    "Newport",
    "Pawtucket",
    "Providence",
    "Warwick",
    "Woonsocket",
  ],
  "South Carolina": [
    "Aiken",
    "Anderson",
    "Bluffton",
    "Cayce",
    "Charleston",
    "Clemson",
    "Columbia",
    "Conway",
    "Easley",
    "Florence",
    "Fort Mill",
    "Goose Creek",
    "Greenville",
    "Greenwood",
    "Greer",
    "Hanahan",
    "Hilton Head Island",
    "Lexington",
    "Mauldin",
    "Mount Pleasant",
    "Myrtle Beach",
    "North Augusta",
    "North Charleston",
    "North Myrtle Beach",
    "Rock Hill",
    "Simpsonville",
    "Spartanburg",
    "Summerville",
    "Sumter",
    "West Columbia",
  ],
  "South Dakota": [
    "Aberdeen",
    "Belle Fourche",
    "Box Elder",
    "Brandon",
    "Brookings",
    "Canton",
    "Dell Rapids",
    "Harrisburg",
    "Hartford",
    "Hot Springs",
    "Huron",
    "Lead",
    "Lennox",
    "Madison",
    "Milbank",
    "Mitchell",
    "Mobridge",
    "North Sioux City",
    "Pierre",
    "Rapid City",
    "Sioux Falls",
    "Sisseton",
    "Spearfish",
    "Sturgis",
    "Summerset",
    "Tea",
    "Vermillion",
    "Watertown",
    "Winner",
    "Yankton",
  ],
  Tennessee: [
    "Bartlett",
    "Brentwood",
    "Bristol",
    "Chattanooga",
    "Clarksville",
    "Cleveland",
    "Collierville",
    "Columbia",
    "Cookeville",
    "Farragut",
    "Franklin",
    "Gallatin",
    "Germantown",
    "Hendersonville",
    "Jackson",
    "Johnson City",
    "Kingsport",
    "Knoxville",
    "La Vergne",
    "Lebanon",
    "Maryville",
    "Memphis",
    "Morristown",
    "Mount Juliet",
    "Murfreesboro",
    "Nashville",
    "Oak Ridge",
    "Shelbyville",
    "Smyrna",
    "Spring Hill",
  ],
  Texas: [
    "Abilene",
    "Amarillo",
    "Arlington",
    "Austin",
    "Brownsville",
    "Carrollton",
    "Corpus Christi",
    "Dallas",
    "Denton",
    "El Paso",
    "Fort Worth",
    "Frisco",
    "Garland",
    "Grand Prairie",
    "Houston",
    "Irving",
    "Killeen",
    "Laredo",
    "Lubbock",
    "Mcallen",
    "Mckinney",
    "Mesquite",
    "Midland",
    "Odessa",
    "Pasadena",
    "Pearland",
    "Plano",
    "Round Rock",
    "San Antonio",
    "Waco",
  ],
  Utah: [
    "Bountiful",
    "Cedar City",
    "Cottonwood Heights",
    "Draper",
    "Eagle Mountain",
    "Herriman",
    "Kearns",
    "Layton",
    "Lehi",
    "Logan",
    "Midvale",
    "Millcreek",
    "Murray",
    "Ogden",
    "Orem",
    "Pleasant Grove",
    "Provo",
    "Riverton",
    "Roy",
    "Salt Lake City",
    "Sandy",
    "Saratoga Springs",
    "South Jordan",
    "Spanish Fork",
    "Springville",
    "St. George",
    "Taylorsville",
    "Tooele",
    "West Jordan",
    "West Valley City",
  ],
  Vermont: [
    "Alburgh",
    "Barre",
    "Barton",
    "Bellows Falls",
    "Burlington",
    "Derby Center",
    "Derby Line",
    "Enosburg Falls",
    "Essex Junction",
    "Hyde Park",
    "Jeffersonville",
    "Johnson",
    "Ludlow",
    "Lyndonville",
    "Manchester",
    "Montpelier",
    "Morrisville",
    "Newport",
    "North Bennington",
    "North Troy",
    "Orleans",
    "Poultney",
    "Rutland",
    "Saxtons River",
    "South Burlington",
    "St. Albans",
    "Swanton",
    "Vergennes",
    "Winooski",
    "Woodstock",
  ],
  Virginia: [
    "Alexandria",
    "Blacksburg",
    "Charlottesville",
    "Chesapeake",
    "Christiansburg",
    "Culpeper",
    "Danville",
    "Fairfax",
    "Fredericksburg",
    "Hampton",
    "Harrisonburg",
    "Herndon",
    "Hopewell",
    "Leesburg",
    "Lynchburg",
    "Manassas",
    "Manassas Park",
    "Newport News",
    "Norfolk",
    "Petersburg",
    "Portsmouth",
    "Radford",
    "Richmond",
    "Roanoke",
    "Salem",
    "Staunton",
    "Suffolk",
    "Virginia Beach",
    "Waynesboro",
    "Winchester",
  ],
  Washington: [
    "Auburn",
    "Bellevue",
    "Bellingham",
    "Bothell",
    "Bremerton",
    "Burien",
    "Edmonds",
    "Everett",
    "Federal Way",
    "Issaquah",
    "Kennewick",
    "Kent",
    "Kirkland",
    "Lacey",
    "Lakewood",
    "Marysville",
    "Olympia",
    "Pasco",
    "Puyallup",
    "Redmond",
    "Renton",
    "Richland",
    "Sammamish",
    "Seattle",
    "Shoreline",
    "Spokane",
    "Spokane Valley",
    "Tacoma",
    "Vancouver",
    "Yakima",
  ],
  "West Virginia": [
    "Barboursville",
    "Beckley",
    "Bluefield",
    "Bridgeport",
    "Buckhannon",
    "Charles",
    "Charleston",
    "Clarksburg",
    "Dunbar",
    "Elkins",
    "Fairmont",
    "Grafton",
    "Huntington",
    "Hurricane",
    "Keyser",
    "Martinsburg",
    "Morgantown",
    "Moundsville",
    "New Martinsville",
    "Nitro",
    "Oak Hill",
    "Parkersburg",
    "Princeton",
    "Ranson Corporation",
    "South Charleston",
    "St. Albans",
    "Vienna",
    "Weirton",
    "Westover",
    "Wheeling",
  ],
  Wisconsin: [
    "Appleton",
    "Beloit",
    "Brookfield",
    "Eau Claire",
    "Fitchburg",
    "Fond Du Lac",
    "Franklin",
    "Green Bay",
    "Greenfield",
    "Janesville",
    "Kenosha",
    "La Crosse",
    "Madison",
    "Manitowoc",
    "Menomonee Falls",
    "Milwaukee",
    "Mount Pleasant",
    "Neenah",
    "New Berlin",
    "Oak Creek",
    "Oshkosh",
    "Racine",
    "Sheboygan",
    "Sun Prairie",
    "Superior",
    "Waukesha",
    "Wausau",
    "Wauwatosa",
    "West Allis",
    "West Bend",
  ],
  Wyoming: [
    "Afton",
    "Bar Nunn",
    "Buffalo",
    "Casper",
    "Cheyenne",
    "Cody",
    "Douglas",
    "Evanston",
    "Evansville",
    "Gillette",
    "Glenrock",
    "Green River",
    "Jackson",
    "Kemmerer",
    "Lander",
    "Laramie",
    "Lovell",
    "Lyman",
    "Mills",
    "Newcastle",
    "Pinedale",
    "Powell",
    "Rawlins",
    "Riverton",
    "Rock Springs",
    "Sheridan",
    "Thermopolis",
    "Torrington",
    "Wheatland",
    "Worland",
  ],
};
