export const CITIES_BY_STATE: Record<string, string[]> = {
  Alabama: [
    "Alabaster",
    "Albertville",
    "Alexander City",
    "Andalusia",
    "Anniston",
    "Arab",
    "Athens",
    "Atmore",
    "Attalla",
    "Auburn",
    "Bay Minette",
    "Bessemer",
    "Birmingham",
    "Boaz",
    "Brewton",
    "Calera",
    "Center Point",
    "Chelsea",
    "Chickasaw",
    "Clanton",
    "Clay",
    "Cullman",
    "Daphne",
    "Decatur",
    "Demopolis",
    "Dothan",
    "Enterprise",
    "Eufaula",
    "Fairfield",
    "Fairhope",
    "Florence",
    "Foley",
    "Fort Payne",
    "Fultondale",
    "Gadsden",
    "Gardendale",
    "Greenville",
    "Gulf Shores",
    "Guntersville",
    "Hamilton",
    "Hartselle",
    "Helena",
    "Homewood",
    "Hoover",
    "Hueytown",
    "Huntsville",
    "Irondale",
    "Jacksonville",
    "Jasper",
    "Lanett",
    "Leeds",
    "Lincoln",
    "Madison",
    "Millbrook",
    "Mobile",
    "Monroeville",
    "Montevallo",
    "Montgomery",
    "Moody",
    "Mountain Brook",
    "Muscle Shoals",
    "Northport",
    "Oneonta",
    "Opelika",
    "Opp",
    "Orange Beach",
    "Oxford",
    "Ozark",
    "Pelham",
    "Pell City",
    "Phenix City",
    "Pike Road",
    "Pinson",
    "Pleasant Grove",
    "Prattville",
    "Prichard",
    "Rainbow City",
    "Roanoke",
    "Robertsdale",
    "Russellville",
    "Saraland",
    "Satsuma",
    "Scottsboro",
    "Selma",
    "Semmes",
    "Sheffield",
    "Smiths Station",
    "Southside",
    "Spanish Fort",
    "Sylacauga",
    "Talladega",
    "Tarrant",
    "Troy",
    "Trussville",
    "Tuscaloosa",
    "Tuscumbia",
    "Tuskegee",
    "Valley",
    "Vestavia Hills",
    "Wetumpka",
  ],
  Alaska: [
    "Adak",
    "Akiak",
    "Akutan",
    "Alakanuk",
    "Ambler",
    "Anaktuvuk Pass",
    "Anchorage",
    "Anderson",
    "Angoon",
    "Aniak",
    "Atqasuk",
    "Bethel",
    "Brevig Mission",
    "Buckland",
    "Chefornak",
    "Chevak",
    "Cordova",
    "Craig",
    "Delta Junction",
    "Dillingham",
    "Eek",
    "Elim",
    "Emmonak",
    "Fairbanks",
    "Fort Yukon",
    "Galena",
    "Gambell",
    "Goodnews Bay",
    "Gustavus",
    "Homer",
    "Hoonah",
    "Hooper Bay",
    "Houston",
    "Huslia",
    "Hydaburg",
    "Juneau",
    "Kachemak",
    "Kake",
    "Kaktovik",
    "Kenai",
    "Ketchikan",
    "Kiana",
    "King Cove",
    "Kivalina",
    "Klawock",
    "Kodiak",
    "Kotlik",
    "Kotzebue",
    "Koyuk",
    "Kwethluk",
    "Lower Kalskag",
    "Manokotak",
    "Marshall",
    "Mcgrath",
    "Mountain Village City",
    "Napakiak",
    "Napaskiak",
    "Nenana",
    "New Stuyahok",
    "Nightmute",
    "Nome",
    "Noorvik",
    "North Pole",
    "Nuiqsut",
    "Nulato",
    "Nunapitchuk",
    "Palmer",
    "Pilot Station",
    "Point Hope",
    "Quinhagak",
    "Russian Mission",
    "Sand Point",
    "Savoonga",
    "Saxman",
    "Scammon Bay",
    "Selawik",
    "Seldovia",
    "Seward",
    "Shaktoolik",
    "Shishmaref",
    "Shungnak",
    "Sitka",
    "Soldotna",
    "St. Mary's",
    "St. Michael",
    "St. Paul City",
    "Stebbins",
    "Tanana",
    "Teller",
    "Thorne Bay",
    "Togiak",
    "Toksook Bay",
    "Unalakleet",
    "Unalaska",
    "Upper Kalskag",
    "Utqiagvik",
    "Valdez",
    "Wainwright",
    "Wasilla",
    "Wrangell",
  ],
  Arizona: [
    "Apache Junction",
    "Avondale",
    "Benson",
    "Bisbee",
    "Buckeye",
    "Bullhead City City",
    "Camp Verde",
    "Carefree",
    "Casa Grande",
    "Cave Creek",
    "Chandler",
    "Chino Valley",
    "Clarkdale",
    "Clifton",
    "Colorado City",
    "Coolidge",
    "Cottonwood",
    "Dewey-humboldt",
    "Douglas",
    "Duncan",
    "Eagar",
    "El Mirage",
    "Eloy",
    "Flagstaff",
    "Florence",
    "Fountain Hills Town",
    "Fredonia",
    "Gila Bend",
    "Gilbert",
    "Glendale",
    "Globe",
    "Goodyear",
    "Guadalupe",
    "Hayden",
    "Holbrook",
    "Huachuca City",
    "Jerome",
    "Kearny",
    "Kingman",
    "Lake Havasu City City",
    "Litchfield Park",
    "Mammoth",
    "Marana",
    "Maricopa",
    "Mesa",
    "Miami",
    "Nogales",
    "Oro Valley",
    "Page",
    "Paradise Valley",
    "Parker",
    "Patagonia",
    "Payson",
    "Peoria",
    "Phoenix",
    "Pima",
    "Pinetop-lakeside",
    "Prescott",
    "Prescott Valley",
    "Quartzsite",
    "Queen Creek",
    "Safford",
    "Sahuarita",
    "San Luis",
    "Scottsdale",
    "Sedona",
    "Show Low",
    "Sierra Vista",
    "Snowflake",
    "Somerton",
    "South Tucson",
    "Springerville",
    "St. Johns",
    "Star Valley",
    "Superior",
    "Surprise",
    "Taylor",
    "Tempe",
    "Thatcher",
    "Tolleson",
    "Tombstone",
    "Tucson",
    "Tusayan",
    "Wellton",
    "Wickenburg",
    "Willcox",
    "Williams",
    "Winkelman",
    "Winslow",
    "Youngtown",
    "Yuma",
  ],
  Arkansas: [
    "Alexander",
    "Alma",
    "Arkadelphia",
    "Ashdown",
    "Atkins",
    "Austin",
    "Barling",
    "Batesville",
    "Beebe",
    "Bella Vista",
    "Benton",
    "Bentonville",
    "Berryville",
    "Blytheville",
    "Booneville",
    "Brookland",
    "Bryant",
    "Cabot",
    "Camden",
    "Cave Springs",
    "Centerton",
    "Cherokee",
    "Clarksville",
    "Conway",
    "Corning",
    "Crossett",
    "Dardanelle",
    "De Queen",
    "Dewitt",
    "Dumas",
    "El Dorado",
    "Elkins",
    "Farmington",
    "Fayetteville",
    "Fordyce",
    "Forrest City",
    "Fort Smith",
    "Gentry",
    "Gosnell",
    "Gravette",
    "Greenbrier",
    "Greenwood",
    "Harrison",
    "Haskell",
    "Heber Springs",
    "Helena-west Helena",
    "Hope",
    "Hot Springs",
    "Jacksonville",
    "Johnson",
    "Jonesboro",
    "Little Rock",
    "Lonoke",
    "Lowell",
    "Magnolia",
    "Malvern",
    "Manila",
    "Marianna",
    "Marion",
    "Maumelle",
    "Mcgehee",
    "Mena",
    "Monticello",
    "Morrilton",
    "Mountain Home",
    "Nashville",
    "Newport",
    "North Little Rock",
    "Osceola",
    "Ozark",
    "Paragould",
    "Paris",
    "Pea Ridge",
    "Piggott",
    "Pine Bluff",
    "Pocahontas",
    "Pottsville",
    "Prairie Grove",
    "Rogers",
    "Russellville",
    "Searcy",
    "Shannon Hills",
    "Sheridan",
    "Sherwood",
    "Siloam Springs",
    "Southside",
    "Springdale",
    "Stuttgart",
    "Texarkana",
    "Tontitown",
    "Trumann",
    "Van Buren",
    "Vilonia",
    "Waldron",
    "Walnut Ridge",
    "Ward",
    "Warren",
    "West Memphis",
    "White Hall",
    "Wynne",
  ],
  California: [
    "Anaheim",
    "Antioch",
    "Bakersfield",
    "Berkeley",
    "Burbank",
    "Carlsbad",
    "Carson",
    "Chico",
    "Chino",
    "Chino Hills",
    "Chula Vista",
    "Citrus Heights",
    "Clovis",
    "Compton",
    "Concord",
    "Corona",
    "Costa Mesa",
    "Daly City City",
    "Downey",
    "El Cajon",
    "El Monte",
    "Elk Grove",
    "Escondido",
    "Fairfield",
    "Fontana",
    "Fremont",
    "Fresno",
    "Fullerton",
    "Garden Grove",
    "Glendale",
    "Hawthorne",
    "Hayward",
    "Hemet",
    "Hesperia",
    "Huntington Beach",
    "Indio",
    "Inglewood",
    "Irvine",
    "Jurupa Valley",
    "Lake Forest",
    "Lancaster",
    "Livermore",
    "Long Beach",
    "Los Angeles",
    "Menifee",
    "Milpitas",
    "Mission Viejo",
    "Modesto",
    "Moreno Valley",
    "Murrieta",
    "Newport Beach",
    "Norwalk",
    "Oakland",
    "Oceanside",
    "Ontario",
    "Orange",
    "Oxnard",
    "Palmdale",
    "Pasadena",
    "Pomona",
    "Rancho Cucamonga",
    "Redding",
    "Redwood City",
    "Rialto",
    "Richmond",
    "Riverside",
    "Roseville",
    "Sacramento",
    "Salinas",
    "San Bernardino",
    "San Buenaventura (ventura)",
    "San Diego",
    "San Francisco",
    "San Jose",
    "San Leandro",
    "San Marcos",
    "San Mateo",
    "Santa Ana",
    "Santa Barbara",
    "Santa Clara",
    "Santa Clarita",
    "Santa Maria",
    "Santa Monica",
    "Santa Rosa",
    "Simi Valley",
    "South Gate",
    "Stockton",
    "Sunnyvale",
    "Temecula",
    "Thousand Oaks",
    "Torrance",
    "Tracy",
    "Vacaville",
    "Vallejo",
    "Victorville",
    "Visalia",
    "Vista",
    "West Covina",
    "Westminster",
    "Whittier",
  ],
  Colorado: [
    "Alamosa",
    "Arvada",
    "Aspen",
    "Aurora",
    "Avon",
    "Basalt",
    "Bennett",
    "Berthoud",
    "Boulder",
    "Breckenridge",
    "Brighton",
    "Broomfield",
    "Brush",
    "Buena Vista",
    "Burlington",
    "Carbondale",
    "Castle Pines",
    "Castle Rock",
    "Cañon City",
    "Centennial",
    "Cherry Hills Village",
    "Colorado Springs",
    "Commerce City",
    "Cortez",
    "Craig",
    "Dacono",
    "Delta",
    "Denver",
    "Durango",
    "Eagle",
    "Eaton",
    "Edgewater",
    "Englewood",
    "Erie",
    "Estes Park",
    "Evans",
    "Federal Heights",
    "Firestone",
    "Florence",
    "Fort Collins",
    "Fort Lupton",
    "Fort Morgan",
    "Fountain",
    "Frederick",
    "Frisco",
    "Fruita",
    "Glendale",
    "Glenwood Springs",
    "Golden",
    "Grand Junction",
    "Greeley",
    "Greenwood Village",
    "Gunnison",
    "Gypsum",
    "Hudson",
    "Johnstown",
    "La Junta",
    "Lafayette",
    "Lakewood",
    "Lamar",
    "Leadville",
    "Littleton",
    "Lochbuie",
    "Lone Tree",
    "Longmont",
    "Louisville",
    "Loveland",
    "Manitou Springs",
    "Mead",
    "Milliken",
    "Monte Vista",
    "Montrose",
    "Monument",
    "New Castle",
    "Northglenn",
    "Orchard City",
    "Palmer Lake",
    "Parker",
    "Pueblo",
    "Rifle",
    "Rocky Ford",
    "Salida",
    "Severance",
    "Sheridan",
    "Silt",
    "Silverthorne",
    "Steamboat Springs",
    "Sterling",
    "Superior",
    "Thornton",
    "Timnath",
    "Trinidad",
    "Vail",
    "Walsenburg",
    "Wellington",
    "Westminster",
    "Wheat Ridge",
    "Windsor",
    "Woodland Park",
    "Yuma",
  ],
  Connecticut: [
    "Ansonia",
    "Bantam",
    "Bridgeport",
    "Bristol",
    "Danbury",
    "Danielson",
    "Derby",
    "Fenwick",
    "Groton",
    "Groton Long Point",
    "Hartford",
    "Jewett City",
    "Litchfield",
    "Meriden",
    "Middletown",
    "Milford",
    "Naugatuck",
    "New Britain",
    "New Haven",
    "New London",
    "Newtown",
    "Norwalk",
    "Norwich",
    "Shelton",
    "Stamford",
    "Stonington",
    "Torrington",
    "Waterbury",
    "West Haven",
    "Woodmont",
  ],
  Delaware: [
    "Arden",
    "Ardencroft",
    "Ardentown",
    "Bellefonte",
    "Bethany Beach",
    "Bethel",
    "Blades",
    "Bowers",
    "Bridgeville",
    "Camden",
    "Cheswold",
    "Clayton",
    "Dagsboro",
    "Delaware City",
    "Delmar",
    "Dewey Beach",
    "Dover",
    "Ellendale",
    "Elsmere",
    "Farmington",
    "Felton",
    "Fenwick Island",
    "Frankford",
    "Frederica",
    "Georgetown",
    "Greenwood",
    "Harrington",
    "Hartly",
    "Henlopen Acres",
    "Houston",
    "Kenton",
    "Laurel",
    "Leipsic",
    "Lewes",
    "Little Creek",
    "Magnolia",
    "Middletown",
    "Milford",
    "Millsboro",
    "Millville",
    "Milton",
    "New Castle",
    "Newark",
    "Newport",
    "Ocean View",
    "Odessa",
    "Rehoboth Beach",
    "Seaford",
    "Selbyville",
    "Slaughter Beach",
    "Smyrna",
    "South Bethany",
    "Townsend",
    "Viola",
    "Wilmington",
    "Woodside",
    "Wyoming",
  ],
  "District of Columbia": [
    "Washington",
  ],
  Florida: [
    "Altamonte Springs",
    "Apopka",
    "Aventura",
    "Boca Raton",
    "Bonita Springs",
    "Boynton Beach",
    "Bradenton",
    "Cape Coral",
    "Casselberry",
    "Clearwater",
    "Clermont",
    "Coconut Creek",
    "Cooper City City",
    "Coral Gables",
    "Coral Springs",
    "Crestview",
    "Cutler Bay",
    "Dania Beach",
    "Davie",
    "Daytona Beach",
    "Deerfield Beach",
    "Deland",
    "Delray Beach",
    "Deltona",
    "Doral",
    "Dunedin",
    "Estero",
    "Fort Lauderdale",
    "Fort Myers",
    "Fort Pierce",
    "Gainesville",
    "Greenacres",
    "Haines City",
    "Hallandale Beach",
    "Hialeah",
    "Hollywood",
    "Homestead",
    "Jacksonville",
    "Jupiter",
    "Kissimmee",
    "Lake Worth",
    "Lakeland",
    "Largo",
    "Lauderdale Lakes",
    "Lauderhill",
    "Margate",
    "Melbourne",
    "Miami",
    "Miami Beach",
    "Miami Gardens",
    "Miami Lakes",
    "Miramar",
    "New Smyrna Beach",
    "North Lauderdale",
    "North Miami",
    "North Miami Beach",
    "North Port",
    "Oakland Park",
    "Ocala",
    "Ocoee",
    "Orlando",
    "Ormond Beach",
    "Oviedo",
    "Palm Bay",
    "Palm Beach Gardens",
    "Palm Coast",
    "Palm Springs",
    "Palmetto Bay",
    "Panama City City",
    "Parkland",
    "Pembroke Pines",
    "Pensacola",
    "Pinellas Park",
    "Plant City",
    "Plantation",
    "Pompano Beach",
    "Port Orange",
    "Port St. Lucie",
    "Riviera Beach",
    "Rockledge",
    "Royal Palm Beach",
    "Sanford",
    "Sarasota",
    "Sebastian",
    "St. Cloud City",
    "St. Petersburg City",
    "Sunrise",
    "Tallahassee",
    "Tamarac",
    "Tampa",
    "Tarpon Springs",
    "Temple Terrace",
    "Titusville",
    "Wellington",
    "West Palm Beach",
    "Weston",
    "Winter Garden",
    "Winter Haven",
    "Winter Park",
    "Winter Springs",
  ],
  Georgia: [
    "Acworth",
    "Albany",
    "Alpharetta",
    "Americus",
    "Athens-clarke County Unified Government (balance)",
    "Atlanta",
    "Augusta-richmond",
    "Bainbridge",
    "Braselton",
    "Brookhaven",
    "Brunswick",
    "Buford",
    "Cairo",
    "Calhoun",
    "Canton",
    "Carrollton",
    "Cartersville",
    "Cedartown",
    "Chamblee",
    "Clarkston",
    "College Park",
    "Columbus",
    "Conyers",
    "Cordele",
    "Covington",
    "Cusseta-chattahoochee County Unified Government",
    "Dallas",
    "Dalton",
    "Decatur",
    "Doraville",
    "Douglas",
    "Douglasville",
    "Dublin",
    "Duluth",
    "Dunwoody",
    "East Point",
    "Fairburn",
    "Fayetteville",
    "Fitzgerald",
    "Forest Park",
    "Fort Oglethorpe",
    "Fort Valley",
    "Gainesville",
    "Garden City",
    "Griffin",
    "Grovetown",
    "Hinesville",
    "Holly Springs",
    "Jefferson City",
    "Jesup",
    "Johns Creek",
    "Kennesaw",
    "Kingsland",
    "Lagrange",
    "Lawrenceville",
    "Lilburn",
    "Loganville",
    "Macon-bibb",
    "Marietta",
    "Mcdonough",
    "Milledgeville",
    "Milton",
    "Monroe",
    "Moultrie",
    "Newnan",
    "Norcross",
    "Peachtree City",
    "Peachtree Corners",
    "Perry",
    "Pooler",
    "Port Wentworth",
    "Powder Springs",
    "Richmond Hill",
    "Rincon",
    "Riverdale",
    "Rome",
    "Roswell",
    "Sandy Springs",
    "Savannah",
    "Smyrna",
    "Snellville",
    "South Fulton",
    "St. Marys",
    "Statesboro",
    "Stockbridge",
    "Stonecrest",
    "Sugar Hill",
    "Suwanee",
    "Thomaston",
    "Thomasville",
    "Tifton",
    "Tucker",
    "Union City",
    "Valdosta",
    "Vidalia",
    "Villa Rica",
    "Warner Robins",
    "Waycross",
    "Winder",
    "Woodstock",
  ],
  Hawaii: [
    "Urban Honolulu",
  ],
  Idaho: [
    "Aberdeen",
    "American Falls",
    "Ammon",
    "Arco",
    "Ashton",
    "Bellevue",
    "Blackfoot",
    "Boise City City",
    "Bonners Ferry",
    "Buhl",
    "Burley",
    "Caldwell",
    "Cascade",
    "Challis",
    "Chubbuck",
    "Coeur D'alene City",
    "Cottonwood",
    "Council",
    "Dalton Gardens",
    "Dover",
    "Driggs",
    "Eagle",
    "Emmett",
    "Filer",
    "Franklin",
    "Fruitland",
    "Garden City",
    "Genesee",
    "Glenns Ferry",
    "Gooding",
    "Grace",
    "Grangeville",
    "Greenleaf",
    "Hagerman",
    "Hailey",
    "Hansen",
    "Hayden",
    "Hazelton",
    "Heyburn",
    "Homedale",
    "Idaho Falls City",
    "Inkom",
    "Iona",
    "Jerome",
    "Kamiah",
    "Kellogg",
    "Ketchum",
    "Kimberly",
    "Kootenai",
    "Kuna",
    "Lapwai",
    "Lewiston",
    "Malad City",
    "Marsing",
    "Mccall",
    "Mccammon",
    "Menan",
    "Meridian",
    "Middleton",
    "Montpelier",
    "Moscow",
    "Mountain Home",
    "Nampa",
    "New Plymouth",
    "Oakley",
    "Orofino",
    "Osburn",
    "Parma",
    "Paul",
    "Payette",
    "Pinehurst",
    "Plummer",
    "Pocatello",
    "Ponderay",
    "Post Falls",
    "Potlatch",
    "Preston",
    "Priest River",
    "Rathdrum",
    "Rexburg",
    "Rigby",
    "Rupert",
    "Salmon",
    "Sandpoint",
    "Shelley",
    "Shoshone",
    "Soda Springs",
    "Spirit Lake",
    "St. Anthony",
    "St. Maries",
    "Star",
    "Sugar City",
    "Sun Valley",
    "Troy",
    "Twin Falls",
    "Ucon",
    "Victor",
    "Weiser",
    "Wendell",
    "Wilder",
  ],
  Illinois: [
    "Addison",
    "Algonquin",
    "Alton",
    "Arlington Heights",
    "Aurora",
    "Bartlett",
    "Batavia",
    "Belleville",
    "Belvidere",
    "Berwyn",
    "Bloomington",
    "Bolingbrook",
    "Buffalo Grove",
    "Burbank",
    "Calumet City",
    "Carbondale",
    "Carol Stream",
    "Carpentersville",
    "Champaign",
    "Chicago",
    "Chicago Heights",
    "Cicero",
    "Collinsville",
    "Crystal Lake",
    "Danville",
    "Decatur",
    "Dekalb",
    "Des Plaines",
    "Downers Grove",
    "East St. Louis",
    "Edwardsville",
    "Elgin",
    "Elk Grove Village",
    "Elmhurst",
    "Elmwood Park",
    "Evanston",
    "Freeport",
    "Galesburg",
    "Glen Ellyn",
    "Glendale Heights",
    "Glenview",
    "Granite City",
    "Gurnee",
    "Hanover Park",
    "Harvey",
    "Highland Park",
    "Hoffman Estates",
    "Homer Glen",
    "Huntley",
    "Joliet",
    "Kankakee",
    "Lake In The Hills",
    "Lansing",
    "Lockport",
    "Lombard",
    "Mchenry",
    "Melrose Park",
    "Moline",
    "Mount Prospect",
    "Mundelein",
    "Naperville",
    "New Lenox",
    "Niles",
    "Normal",
    "North Chicago",
    "Northbrook",
    "O'fallon",
    "Oak Forest",
    "Oak Lawn",
    "Oak Park",
    "Orland Park",
    "Oswego",
    "Palatine",
    "Park Ridge",
    "Pekin",
    "Peoria",
    "Plainfield",
    "Quincy",
    "Rock Island",
    "Rockford",
    "Rolling Meadows",
    "Romeoville",
    "Round Lake Beach",
    "Schaumburg",
    "Skokie",
    "South Elgin",
    "Springfield",
    "St. Charles",
    "Streamwood",
    "Tinley Park",
    "Urbana",
    "Vernon Hills",
    "Waukegan",
    "West Chicago",
    "Westmont",
    "Wheaton",
    "Wheeling",
    "Wilmette",
    "Woodridge",
    "Woodstock",
  ],
  Indiana: [
    "Anderson",
    "Angola",
    "Auburn",
    "Avon",
    "Bargersville",
    "Batesville",
    "Bedford",
    "Beech Grove",
    "Bloomington",
    "Bluffton",
    "Brazil",
    "Brownsburg",
    "Carmel",
    "Cedar Lake",
    "Charlestown",
    "Chesterton",
    "Clarksville",
    "Columbia City",
    "Columbus",
    "Connersville",
    "Crawfordsville",
    "Crown Point",
    "Danville",
    "Decatur",
    "Dyer",
    "East Chicago",
    "Elkhart",
    "Ellettsville",
    "Elwood",
    "Evansville",
    "Fishers",
    "Fort Wayne",
    "Frankfort",
    "Franklin",
    "Gary",
    "Goshen",
    "Greencastle",
    "Greenfield",
    "Greensburg",
    "Greenwood",
    "Griffith",
    "Hammond",
    "Highland",
    "Hobart",
    "Huntertown",
    "Huntington",
    "Indianapolis",
    "Jasper",
    "Jeffersonville",
    "Kendallville",
    "Kokomo",
    "La Porte",
    "Lafayette",
    "Lake Station",
    "Lawrence",
    "Lebanon",
    "Logansport",
    "Lowell",
    "Madison",
    "Marion",
    "Martinsville",
    "Mccordsville",
    "Merrillville",
    "Michigan City",
    "Mishawaka",
    "Mooresville",
    "Muncie",
    "Munster",
    "Nappanee",
    "New Albany",
    "New Castle",
    "New Haven",
    "Noblesville",
    "North Vernon",
    "Peru",
    "Plainfield",
    "Plymouth",
    "Portage",
    "Princeton",
    "Richmond",
    "Schererville",
    "Scottsburg",
    "Sellersburg",
    "Seymour",
    "Shelbyville",
    "South Bend",
    "Speedway",
    "St. John",
    "Tell City",
    "Terre Haute",
    "Valparaiso",
    "Vincennes",
    "Wabash",
    "Warsaw",
    "Washington",
    "West Lafayette",
    "Westfield",
    "Whitestown",
    "Yorktown",
    "Zionsville",
  ],
  Iowa: [
    "Adel",
    "Algona",
    "Altoona",
    "Ames",
    "Anamosa",
    "Ankeny",
    "Asbury",
    "Atlantic City",
    "Bettendorf",
    "Bondurant",
    "Boone",
    "Burlington",
    "Camanche",
    "Carlisle",
    "Carroll",
    "Cedar Falls City",
    "Cedar Rapids",
    "Centerville",
    "Chariton",
    "Charles City",
    "Cherokee",
    "Clarinda",
    "Clear Lake",
    "Clinton",
    "Clive",
    "Coralville",
    "Council Bluffs",
    "Creston",
    "Davenport",
    "Decorah",
    "Denison",
    "Des Moines City",
    "Dewitt",
    "Dubuque",
    "Dyersville",
    "Eldridge",
    "Estherville",
    "Evansdale",
    "Fairfield",
    "Forest City",
    "Fort Dodge",
    "Fort Madison",
    "Glenwood",
    "Grimes",
    "Grinnell",
    "Hampton",
    "Harlan",
    "Hiawatha",
    "Humboldt",
    "Huxley",
    "Independence",
    "Indianola",
    "Iowa City City",
    "Iowa Falls City",
    "Jefferson City",
    "Johnston",
    "Keokuk",
    "Knoxville",
    "Le Mars",
    "Manchester",
    "Maquoketa",
    "Marion",
    "Marshalltown",
    "Mason City",
    "Mount Pleasant",
    "Mount Vernon",
    "Muscatine",
    "Nevada",
    "Newton",
    "North Liberty",
    "Norwalk",
    "Oelwein",
    "Orange City",
    "Osceola",
    "Oskaloosa",
    "Ottumwa",
    "Pella",
    "Perry",
    "Pleasant Hill",
    "Polk City",
    "Red Oak",
    "Sergeant Bluff",
    "Sheldon",
    "Shenandoah",
    "Sioux Center",
    "Sioux City City",
    "Spencer",
    "Spirit Lake",
    "Storm Lake",
    "Tiffin",
    "Urbandale",
    "Vinton",
    "Washington",
    "Waterloo",
    "Waukee",
    "Waverly",
    "Webster City",
    "West Des Moines",
    "Windsor Heights",
    "Winterset",
  ],
  Kansas: [
    "Abilene",
    "Andover",
    "Arkansas City",
    "Atchison",
    "Augusta",
    "Baldwin City",
    "Basehor",
    "Baxter Springs",
    "Bel Aire",
    "Beloit",
    "Bonner Springs",
    "Burlington",
    "Chanute",
    "Clay Center",
    "Clearwater",
    "Coffeyville",
    "Colby",
    "Columbus",
    "Concordia",
    "De Soto",
    "Derby",
    "Dodge City",
    "Edwardsville",
    "El Dorado",
    "Ellsworth",
    "Emporia",
    "Eudora",
    "Fairway",
    "Fort Scott",
    "Frontenac",
    "Galena",
    "Garden City",
    "Gardner",
    "Garnett",
    "Girard",
    "Goddard",
    "Goodland",
    "Great Bend",
    "Hays",
    "Haysville",
    "Hesston",
    "Hiawatha",
    "Hillsboro",
    "Holton",
    "Hugoton",
    "Hutchinson",
    "Independence",
    "Iola",
    "Junction City",
    "Kansas City City",
    "Kingman",
    "Lansing",
    "Larned",
    "Lawrence",
    "Leavenworth",
    "Leawood",
    "Lenexa",
    "Liberal",
    "Lindsborg",
    "Louisburg",
    "Lyons",
    "Maize",
    "Manhattan",
    "Marysville",
    "Mcpherson",
    "Merriam",
    "Mission",
    "Mission Hills",
    "Mulvane",
    "Newton",
    "Norton",
    "Olathe",
    "Osage City",
    "Osawatomie",
    "Ottawa",
    "Overland Park",
    "Paola",
    "Park City",
    "Parsons",
    "Pittsburg",
    "Prairie",
    "Pratt",
    "Roeland Park",
    "Rose Hill",
    "Russell",
    "Sabetha",
    "Salina",
    "Scott City",
    "Shawnee",
    "South Hutchinson",
    "Spring Hill",
    "St. Marys",
    "Tonganoxie",
    "Topeka",
    "Ulysses",
    "Valley Center",
    "Wamego",
    "Wellington",
    "Wichita",
    "Winfield",
  ],
  Kentucky: [
    "Alexandria",
    "Ashland",
    "Bardstown",
    "Beaver Dam",
    "Bellevue",
    "Benton",
    "Berea",
    "Bowling Green",
    "Campbellsville",
    "Carrollton",
    "Central City",
    "Cold Spring",
    "Columbia",
    "Corbin",
    "Covington",
    "Crescent Springs",
    "Crestwood",
    "Crittenden",
    "Cynthiana",
    "Danville",
    "Dayton",
    "Douglass Hills",
    "Edgewood",
    "Elizabethtown",
    "Elsmere",
    "Erlanger",
    "Flatwoods",
    "Florence",
    "Fort Mitchell",
    "Fort Thomas",
    "Fort Wright",
    "Frankfort",
    "Franklin",
    "Georgetown",
    "Glasgow",
    "Grayson",
    "Greenville",
    "Harrodsburg",
    "Hazard",
    "Henderson",
    "Highland Heights",
    "Hillview",
    "Hopkinsville",
    "Hurstbourne",
    "Independence",
    "Jeffersontown",
    "La Grange",
    "Lancaster",
    "Lawrenceburg",
    "Lebanon",
    "Leitchfield",
    "Lexington-fayette",
    "London",
    "Louisville/jefferson",
    "Ludlow",
    "Lyndon",
    "Madisonville",
    "Mayfield",
    "Maysville",
    "Middlesborough",
    "Middletown",
    "Monticello",
    "Morehead",
    "Morganfield",
    "Mount Sterling",
    "Mount Washington",
    "Murray",
    "Newport",
    "Nicholasville",
    "Oak Grove",
    "Owensboro",
    "Paducah",
    "Paintsville",
    "Paris",
    "Pikeville",
    "Prestonsburg",
    "Princeton",
    "Prospect",
    "Radcliff",
    "Richmond",
    "Russellville",
    "Scottsville",
    "Shelbyville",
    "Shepherdsville",
    "Shively",
    "Somerset",
    "Southgate",
    "St. Matthews",
    "Stanford",
    "Taylor Mill",
    "Union",
    "Versailles",
    "Villa Hills",
    "Vine Grove",
    "Walton",
    "West Liberty",
    "Williamsburg",
    "Williamstown",
    "Wilmore",
    "Winchester",
  ],
  Louisiana: [
    "Abbeville",
    "Addis",
    "Alexandria",
    "Amite City",
    "Baker",
    "Ball",
    "Bastrop",
    "Baton Rouge",
    "Berwick",
    "Blanchard",
    "Bogalusa",
    "Bossier City City",
    "Breaux Bridge",
    "Broussard",
    "Bunkie",
    "Carencro",
    "Central",
    "Church Point",
    "Covington",
    "Crowley",
    "Delhi",
    "Denham Springs",
    "Dequincy",
    "Deridder",
    "Donaldsonville",
    "Eunice",
    "Farmerville",
    "Ferriday",
    "Franklin",
    "Franklinton",
    "Gonzales",
    "Grambling",
    "Gramercy",
    "Greenwood",
    "Gretna",
    "Hammond",
    "Harahan",
    "Haughton",
    "Homer",
    "Houma",
    "Iowa",
    "Jackson",
    "Jeanerette",
    "Jena",
    "Jennings",
    "Jonesboro",
    "Kaplan",
    "Kenner",
    "Lafayette",
    "Lake Arthur",
    "Lake Charles",
    "Lake Providence",
    "Leesville",
    "Lutcher",
    "Mamou",
    "Mandeville",
    "Mansfield",
    "Marksville",
    "Minden",
    "Monroe",
    "Morgan City",
    "Natchitoches",
    "New Iberia",
    "New Orleans",
    "New Roads",
    "Oakdale",
    "Opelousas",
    "Patterson",
    "Pineville",
    "Plaquemine",
    "Ponchatoula",
    "Port Allen",
    "Rayne",
    "Rayville",
    "Richwood",
    "Ruston",
    "Scott",
    "Shreveport",
    "Slidell",
    "Springhill",
    "St. Gabriel",
    "St. Martinville",
    "Sterlington",
    "Sulphur",
    "Sunset",
    "Tallulah",
    "Thibodaux",
    "Vidalia",
    "Ville Platte",
    "Vinton",
    "Vivian",
    "Walker",
    "Welsh",
    "West Monroe",
    "Westlake",
    "Westwego",
    "Winnfield",
    "Winnsboro",
    "Youngsville",
    "Zachary",
  ],
  Maine: [
    "Auburn",
    "Augusta",
    "Bangor",
    "Bath",
    "Belfast",
    "Biddeford",
    "Brewer",
    "Calais",
    "Caribou",
    "Eastport",
    "Ellsworth",
    "Gardiner",
    "Hallowell",
    "Lewiston",
    "Old",
    "Portland",
    "Presque Isle",
    "Rockland",
    "Saco",
    "Sanford",
    "South Portland",
    "Waterville",
    "Westbrook",
  ],
  Maryland: [
    "Aberdeen",
    "Annapolis",
    "Baltimore",
    "Bel Air",
    "Berlin",
    "Berwyn Heights",
    "Bladensburg",
    "Boonsboro",
    "Bowie",
    "Brentwood",
    "Brunswick",
    "Cambridge",
    "Capitol Heights",
    "Centreville",
    "Charlestown",
    "Chesapeake Beach",
    "Chestertown",
    "Cheverly",
    "Chevy Chase",
    "Chevy Chase View",
    "College Park",
    "Colmar Manor",
    "Cottage City",
    "Crisfield",
    "Cumberland",
    "Delmar",
    "Denton",
    "District Heights",
    "Easton",
    "Edmonston",
    "Elkton",
    "Emmitsburg",
    "Fairmount Heights",
    "Federalsburg",
    "Forest Heights",
    "Frederick",
    "Frostburg",
    "Fruitland",
    "Gaithersburg",
    "Garrett Park",
    "Glenarden",
    "Greenbelt",
    "Greensboro",
    "Hagerstown",
    "Hampstead",
    "Hancock",
    "Havre De Grace",
    "Hebron",
    "Hurlock",
    "Hyattsville",
    "Indian Head",
    "Keedysville",
    "Kensington",
    "La Plata",
    "Landover Hills",
    "Laurel",
    "Leonardtown",
    "Lonaconing",
    "Manchester",
    "Martin's Additions",
    "Middletown",
    "Morningside",
    "Mount Airy",
    "Mount Rainier",
    "Mountain Lake Park",
    "Myersville",
    "New Carrollton",
    "New Windsor",
    "North Beach",
    "North East",
    "Oakland",
    "Ocean City",
    "Perryville",
    "Pittsville",
    "Pocomoke City",
    "Poolesville",
    "Princess Anne",
    "Ridgely",
    "Rising Sun",
    "Riverdale Park",
    "Rock Hall",
    "Rockville",
    "Salisbury",
    "Seat Pleasant",
    "Smithsburg",
    "Snow Hill",
    "Somerset",
    "St. Michaels",
    "Sykesville",
    "Takoma Park",
    "Taneytown",
    "Thurmont",
    "Trappe",
    "University Park",
    "Walkersville",
    "Westernport",
    "Westminster",
    "Willards",
    "Williamsport",
    "Woodsboro",
  ],
  Massachusetts: [
    "Agawam",
    "Amesbury",
    "Attleboro",
    "Barnstable",
    "Beverly",
    "Boston",
    "Braintree",
    "Bridgewater",
    "Brockton",
    "Cambridge",
    "Chelsea",
    "Chicopee",
    "Easthampton",
    "Everett",
    "Fall River",
    "Fitchburg",
    "Framingham",
    "Franklin",
    "Gardner",
    "Gloucester",
    "Greenfield",
    "Haverhill",
    "Holyoke",
    "Lawrence",
    "Leominster",
    "Lowell",
    "Lynn",
    "Malden",
    "Marlborough",
    "Medford",
    "Melrose",
    "Methuen",
    "New Bedford",
    "Newburyport",
    "Newton",
    "North Adams",
    "Northampton",
    "Palmer",
    "Peabody",
    "Pittsfield",
    "Quincy",
    "Randolph",
    "Revere",
    "Salem",
    "Somerville",
    "Southbridge",
    "Springfield",
    "Taunton",
    "Waltham",
    "Watertown",
    "West Springfield",
    "Westfield",
    "Weymouth",
    "Winthrop",
    "Woburn",
    "Worcester",
  ],
  Michigan: [
    "Adrian",
    "Allen Park",
    "Alpena",
    "Ann Arbor",
    "Auburn Hills",
    "Battle Creek",
    "Bay City",
    "Benton Harbor",
    "Berkley",
    "Beverly Hills",
    "Big Rapids",
    "Birmingham",
    "Burton",
    "Cadillac",
    "Clawson",
    "Coldwater",
    "Dearborn",
    "Dearborn Heights",
    "Detroit",
    "East Grand Rapids",
    "East Lansing",
    "Eastpointe",
    "Ecorse",
    "Escanaba",
    "Farmington",
    "Farmington Hills",
    "Fenton",
    "Ferndale",
    "Flat Rock",
    "Flint",
    "Fraser",
    "Garden City",
    "Grand Haven",
    "Grand Rapids",
    "Grandville",
    "Grosse Pointe Farms",
    "Grosse Pointe Park",
    "Grosse Pointe Woods",
    "Hamtramck",
    "Harper Woods",
    "Hazel Park",
    "Highland Park",
    "Holland",
    "Howell",
    "Inkster",
    "Ionia",
    "Jackson",
    "Kalamazoo",
    "Kentwood",
    "Lansing",
    "Lincoln Park",
    "Livonia",
    "Madison Heights",
    "Marquette",
    "Marysville",
    "Melvindale",
    "Midland",
    "Monroe",
    "Mount Clemens",
    "Mount Pleasant",
    "Muskegon",
    "Muskegon Heights",
    "New Baltimore",
    "Niles",
    "Norton Shores",
    "Novi",
    "Oak Park",
    "Owosso",
    "Plymouth",
    "Pontiac",
    "Port Huron",
    "Portage",
    "Riverview",
    "Rochester",
    "Rochester Hills",
    "Romulus",
    "Roseville",
    "Royal Oak",
    "Saginaw",
    "Saline",
    "Sault Ste. Marie",
    "South Lyon",
    "Southfield",
    "Southgate",
    "St. Clair Shores",
    "Sterling Heights",
    "Sturgis",
    "Taylor",
    "Traverse City",
    "Trenton",
    "Troy",
    "Walker",
    "Warren",
    "Wayne",
    "Westland",
    "Wixom",
    "Woodhaven",
    "Wyandotte",
    "Wyoming",
    "Ypsilanti",
  ],
  Minnesota: [
    "Albert Lea",
    "Alexandria",
    "Andover",
    "Anoka",
    "Apple Valley",
    "Arden Hills",
    "Austin",
    "Bemidji",
    "Big Lake",
    "Blaine",
    "Bloomington",
    "Brainerd",
    "Brooklyn Center",
    "Brooklyn Park",
    "Buffalo",
    "Burnsville",
    "Champlin",
    "Chanhassen",
    "Chaska",
    "Cloquet",
    "Columbia Heights",
    "Coon Rapids",
    "Cottage Grove",
    "Crystal",
    "Duluth",
    "Eagan",
    "East Bethel",
    "Eden Prairie",
    "Edina",
    "Elk River",
    "Fairmont",
    "Faribault",
    "Farmington",
    "Fergus Falls",
    "Forest Lake",
    "Fridley",
    "Golden Valley",
    "Grand Rapids",
    "Ham Lake",
    "Hastings",
    "Hermantown",
    "Hibbing",
    "Hopkins",
    "Hugo",
    "Hutchinson",
    "Inver Grove Heights",
    "Lakeville",
    "Lino Lakes",
    "Little Canada",
    "Mankato",
    "Maple Grove",
    "Maplewood",
    "Marshall",
    "Mendota Heights",
    "Minneapolis",
    "Minnetonka",
    "Monticello",
    "Moorhead",
    "Mounds View",
    "New Brighton",
    "New Hope",
    "New Ulm",
    "North Branch",
    "North Mankato",
    "North St. Paul",
    "Northfield",
    "Oakdale",
    "Otsego",
    "Owatonna",
    "Plymouth",
    "Prior Lake",
    "Ramsey",
    "Red Wing",
    "Richfield",
    "Robbinsdale",
    "Rochester",
    "Rogers",
    "Rosemount",
    "Roseville",
    "Sartell",
    "Sauk Rapids",
    "Savage",
    "Shakopee",
    "Shoreview",
    "South St. Paul",
    "St. Cloud City",
    "St. Louis Park City",
    "St. Michael",
    "St. Paul City",
    "St. Peter",
    "Stillwater",
    "Vadnais Heights",
    "Victoria",
    "Waconia",
    "West St. Paul",
    "White Bear Lake",
    "Willmar",
    "Winona",
    "Woodbury",
    "Worthington",
  ],
  Mississippi: [
    "Aberdeen",
    "Amory",
    "Baldwyn",
    "Batesville",
    "Bay St. Louis",
    "Biloxi",
    "Booneville",
    "Brandon",
    "Brookhaven",
    "Byram",
    "Canton",
    "Carthage",
    "Clarksdale",
    "Cleveland",
    "Clinton",
    "Collins",
    "Columbia",
    "Columbus",
    "Corinth",
    "Crystal Springs",
    "D'iberville",
    "Diamondhead",
    "Durant",
    "Ellisville",
    "Eupora",
    "Farmington",
    "Florence",
    "Flowood",
    "Forest",
    "Fulton",
    "Gautier",
    "Greenville",
    "Greenwood",
    "Grenada",
    "Gulfport",
    "Guntown",
    "Hattiesburg",
    "Hazlehurst",
    "Hernando",
    "Hollandale",
    "Holly Springs",
    "Horn Lake",
    "Houston",
    "Indianola",
    "Iuka",
    "Jackson",
    "Kosciusko",
    "Laurel",
    "Leland",
    "Long Beach",
    "Louisville",
    "Lucedale",
    "Lumberton",
    "Macon",
    "Madison",
    "Magee",
    "Magnolia",
    "Mccomb",
    "Mendenhall",
    "Meridian",
    "Moorhead",
    "Morton",
    "Moss Point",
    "Natchez",
    "New Albany",
    "Newton",
    "Ocean Springs",
    "Okolona",
    "Olive Branch",
    "Oxford",
    "Pascagoula",
    "Pass Christian",
    "Pearl",
    "Petal",
    "Philadelphia",
    "Picayune",
    "Pontotoc",
    "Poplarville",
    "Purvis",
    "Quitman",
    "Raymond",
    "Richland",
    "Ridgeland",
    "Ripley",
    "Ruleville",
    "Saltillo",
    "Senatobia",
    "Southaven",
    "Starkville",
    "Tupelo",
    "Tutwiler",
    "Verona",
    "Vicksburg",
    "Water Valley",
    "Waveland",
    "Waynesboro",
    "West Point",
    "Wiggins",
    "Winona",
    "Yazoo City",
  ],
  Missouri: [
    "Arnold",
    "Ballwin",
    "Bellefontaine Neighbors",
    "Belton",
    "Berkeley",
    "Blue Springs",
    "Bolivar",
    "Boonville",
    "Branson",
    "Brentwood",
    "Bridgeton",
    "Cameron",
    "Cape Girardeau",
    "Carl Junction",
    "Carthage",
    "Chesterfield",
    "Chillicothe",
    "Clayton",
    "Clinton",
    "Columbia",
    "Crestwood",
    "Creve Coeur",
    "Dardenne Prairie",
    "Des Peres",
    "Ellisville",
    "Eureka",
    "Excelsior Springs",
    "Farmington",
    "Ferguson",
    "Festus",
    "Florissant",
    "Fulton",
    "Gladstone",
    "Grain Valley",
    "Grandview",
    "Hannibal",
    "Harrisonville",
    "Hazelwood",
    "Independence",
    "Jackson",
    "Jefferson City City",
    "Jennings",
    "Joplin",
    "Kansas City City",
    "Kearney",
    "Kennett",
    "Kirksville",
    "Kirkwood",
    "Ladue",
    "Lake St. Louis",
    "Lebanon",
    "Lee's Summit",
    "Liberty",
    "Manchester",
    "Maplewood",
    "Marshall",
    "Maryland Heights",
    "Maryville",
    "Mexico",
    "Moberly",
    "Monett",
    "Neosho",
    "Nevada",
    "Nixa",
    "O'fallon",
    "Oak Grove",
    "Olivette",
    "Overland",
    "Ozark",
    "Park Hills",
    "Perryville",
    "Pleasant Hill",
    "Poplar Bluff",
    "Raymore",
    "Raytown",
    "Republic",
    "Richmond Heights",
    "Rolla",
    "Sedalia",
    "Sikeston",
    "Smithville",
    "Springfield",
    "St. Ann",
    "St. Charles",
    "St. Joseph City",
    "St. Louis City",
    "St. Peters",
    "Sunset Hills",
    "Town And Country",
    "Troy",
    "Union",
    "University City",
    "Warrensburg",
    "Warrenton",
    "Washington",
    "Webb City",
    "Webster Groves",
    "Wentzville",
    "West Plains",
    "Wildwood",
  ],
  Montana: [
    "Alberton",
    "Anaconda-deer Lodge",
    "Bainville",
    "Baker",
    "Belgrade",
    "Belt",
    "Big Sandy",
    "Big Timber",
    "Billings",
    "Boulder",
    "Bozeman",
    "Bridger",
    "Broadus",
    "Browning",
    "Butte-silver Bow (balance)",
    "Cascade",
    "Chester",
    "Chinook",
    "Choteau",
    "Circle",
    "Clyde Park",
    "Colstrip",
    "Columbia Falls",
    "Columbus",
    "Conrad",
    "Culbertson",
    "Cut Bank",
    "Darby",
    "Deer Lodge",
    "Dillon",
    "Drummond",
    "Dutton",
    "East Helena",
    "Ekalaka",
    "Ennis",
    "Eureka",
    "Fairfield",
    "Fairview",
    "Forsyth",
    "Fort Benton",
    "Fort Peck",
    "Fromberg",
    "Geraldine",
    "Glasgow",
    "Glendive",
    "Great Falls",
    "Hamilton",
    "Hardin",
    "Harlem",
    "Harlowton",
    "Havre",
    "Helena",
    "Hot Springs",
    "Hysham",
    "Joliet",
    "Jordan",
    "Kalispell",
    "Laurel",
    "Lewistown",
    "Libby",
    "Livingston",
    "Lodge Grass",
    "Malta",
    "Manhattan",
    "Miles City",
    "Missoula",
    "Nashua",
    "Philipsburg",
    "Pinesdale",
    "Plains",
    "Plentywood",
    "Polson",
    "Poplar",
    "Red Lodge",
    "Ronan",
    "Roundup",
    "Ryegate",
    "Scobey",
    "Shelby",
    "Sheridan",
    "Sidney",
    "St. Ignatius",
    "Stanford",
    "Stevensville",
    "Sunburst",
    "Superior",
    "Terry",
    "Thompson Falls",
    "Three Forks",
    "Townsend",
    "Troy",
    "Twin Bridges",
    "Valier",
    "Walkerville",
    "West Yellowstone",
    "White Sulphur Springs",
    "Whitefish",
    "Whitehall",
    "Wibaux",
    "Wolf Point",
  ],
  Nebraska: [
    "Ainsworth",
    "Albion",
    "Alliance",
    "Alma",
    "Arlington",
    "Ashland",
    "Atkinson",
    "Auburn",
    "Aurora",
    "Battle Creek",
    "Beatrice",
    "Bellevue",
    "Bennington",
    "Blair",
    "Bridgeport",
    "Broken Bow",
    "Burwell",
    "Central City",
    "Chadron",
    "Columbus",
    "Cozad",
    "Crete",
    "Dakota City",
    "David City",
    "Eagle",
    "Fairbury",
    "Falls City",
    "Fremont",
    "Fullerton",
    "Geneva",
    "Gering",
    "Gibbon",
    "Gordon",
    "Gothenburg",
    "Grand Island",
    "Grant",
    "Gretna",
    "Hartington",
    "Hastings",
    "Hebron",
    "Hickman",
    "Holdrege",
    "Imperial",
    "Kearney",
    "Kimball",
    "La Vista",
    "Lexington",
    "Lincoln",
    "Louisville",
    "Madison",
    "Mccook",
    "Milford",
    "Minden",
    "Mitchell",
    "Nebraska City",
    "Neligh",
    "Norfolk",
    "North Bend",
    "North Platte",
    "O'neill",
    "Oakland",
    "Ogallala",
    "Omaha",
    "Ord",
    "Papillion",
    "Pender",
    "Pierce",
    "Plainview",
    "Plattsmouth",
    "Ralston",
    "Ravenna",
    "Schuyler",
    "Scottsbluff",
    "Seward",
    "Sidney",
    "South Sioux City",
    "Springfield",
    "St. Paul City",
    "Stanton",
    "Stromsburg",
    "Superior",
    "Sutherland",
    "Sutton",
    "Syracuse",
    "Tecumseh",
    "Tekamah",
    "Terrytown",
    "Valentine",
    "Valley",
    "Wahoo",
    "Wakefield",
    "Waverly",
    "Wayne",
    "West Point",
    "Wilber",
    "Wisner",
    "Wood River",
    "Wymore",
    "York",
    "Yutan",
  ],
  Nevada: [
    "Boulder City",
    "Caliente",
    "Carlin",
    "Carson",
    "Elko",
    "Ely",
    "Fallon",
    "Fernley",
    "Henderson",
    "Las Vegas",
    "Lovelock",
    "Mesquite",
    "North Las Vegas",
    "Reno",
    "Sparks",
    "Wells",
    "West Wendover",
    "Winnemucca",
    "Yerington",
  ],
  "New Hampshire": [
    "Berlin",
    "Claremont",
    "Concord",
    "Dover",
    "Franklin",
    "Keene",
    "Laconia",
    "Lebanon",
    "Manchester",
    "Nashua",
    "Portsmouth",
    "Rochester",
    "Somersworth",
  ],
  "New Jersey": [
    "Asbury Park",
    "Atlantic City City",
    "Bayonne",
    "Beachwood",
    "Bellmawr",
    "Bergenfield",
    "Bridgeton",
    "Camden",
    "Carteret",
    "Cliffside Park",
    "Clifton",
    "Collingswood",
    "Dover",
    "Dumont",
    "East Orange",
    "Eatontown",
    "Edgewater",
    "Elizabeth",
    "Elmwood Park",
    "Englewood",
    "Fair Lawn",
    "Fairview",
    "Florham Park",
    "Fort Lee",
    "Franklin Lakes",
    "Freehold",
    "Garfield",
    "Glassboro",
    "Glen Rock",
    "Gloucester City",
    "Guttenberg",
    "Hackensack",
    "Haddonfield",
    "Hammonton",
    "Harrison",
    "Hasbrouck Heights",
    "Hawthorne",
    "Highland Park",
    "Hoboken",
    "Hopatcong",
    "Jersey City",
    "Kearny",
    "Linden",
    "Lindenwold",
    "Little Ferry",
    "Lodi",
    "Long Branch",
    "Madison",
    "Metuchen",
    "Middlesex",
    "Millville",
    "Morristown",
    "New Brunswick",
    "New Milford",
    "New Providence",
    "Newark",
    "North Arlington",
    "North Plainfield",
    "Oakland",
    "Ocean City",
    "Palisades Park",
    "Paramus",
    "Passaic",
    "Paterson",
    "Perth Amboy",
    "Phillipsburg",
    "Plainfield",
    "Pleasantville",
    "Point Pleasant",
    "Pompton Lakes",
    "Princeton",
    "Rahway",
    "Ramsey",
    "Red Bank",
    "Ridgefield",
    "Ridgefield Park",
    "Ridgewood",
    "Ringwood",
    "River Edge",
    "Roselle",
    "Roselle Park",
    "Rutherford",
    "Sayreville",
    "Secaucus",
    "Somerville",
    "South Plainfield",
    "South River",
    "Summit",
    "Tenafly",
    "Tinton Falls",
    "Totowa",
    "Trenton",
    "Union City",
    "Vineland",
    "Wallington",
    "Wanaque",
    "West New York",
    "Westfield",
    "Westwood",
    "Woodland Park",
  ],
  "New Mexico": [
    "Alamogordo",
    "Albuquerque",
    "Angel Fire",
    "Anthony",
    "Artesia",
    "Aztec",
    "Bayard",
    "Belen",
    "Bernalillo",
    "Bloomfield",
    "Bosque Farms",
    "Capitan",
    "Carlsbad",
    "Carrizozo",
    "Causey",
    "Chama",
    "Cimarron",
    "Clayton",
    "Cloudcroft",
    "Clovis",
    "Columbus",
    "Corona",
    "Corrales",
    "Cuba",
    "Deming",
    "Des Moines Village",
    "Dexter",
    "Dora",
    "Eagle Nest",
    "Edgewood",
    "Elephant Butte",
    "Elida",
    "Española",
    "Estancia",
    "Eunice",
    "Farmington",
    "Floyd",
    "Fort Sumner",
    "Gallup",
    "Grady",
    "Grants",
    "Hagerman",
    "Hatch",
    "Hobbs",
    "Hope",
    "Hurley",
    "Jal",
    "Jemez Springs",
    "Kirtland",
    "Lake Arthur",
    "Las Cruces",
    "Las Vegas",
    "Logan",
    "Lordsburg",
    "Los Lunas",
    "Los Ranchos De Albuquerque",
    "Loving",
    "Lovington",
    "Magdalena",
    "Maxwell",
    "Melrose",
    "Mesilla",
    "Milan",
    "Moriarty",
    "Mosquero",
    "Mountainair",
    "Pecos",
    "Peralta",
    "Portales",
    "Questa",
    "Raton",
    "Red River",
    "Reserve",
    "Rio Communities",
    "Rio Rancho",
    "Roswell",
    "Roy",
    "Ruidoso",
    "Ruidoso Downs",
    "San Jon",
    "San Ysidro",
    "Santa Clara",
    "Santa Fe",
    "Santa Rosa",
    "Silver City",
    "Socorro",
    "Springer",
    "Sunland Park",
    "Taos",
    "Tatum",
    "Texico",
    "Tijeras",
    "Truth Or Consequences",
    "Tucumcari",
    "Tularosa",
    "Vaughn",
    "Virden",
    "Wagon Mound",
    "Willard",
    "Williamsburg",
  ],
  "New York": [
    "Airmont",
    "Albany",
    "Amityville",
    "Amsterdam",
    "Auburn",
    "Babylon",
    "Batavia",
    "Beacon",
    "Binghamton",
    "Buffalo",
    "Canandaigua",
    "Cohoes",
    "Corning",
    "Cortland",
    "Depew",
    "Dobbs Ferry",
    "Dunkirk",
    "East Rockaway",
    "Elmira",
    "Endicott",
    "Farmingdale",
    "Floral Park",
    "Fredonia",
    "Freeport",
    "Fulton",
    "Garden City",
    "Geneva",
    "Glen Cove",
    "Glens Falls",
    "Gloversville",
    "Great Neck",
    "Hamburg",
    "Harrison",
    "Haverstraw",
    "Hempstead",
    "Ithaca",
    "Jamestown",
    "Johnson City",
    "Kenmore",
    "Kingston",
    "Kiryas Joel",
    "Lackawanna",
    "Lake Grove",
    "Lancaster",
    "Lindenhurst",
    "Lockport",
    "Long Beach",
    "Lynbrook",
    "Mamaroneck",
    "Massapequa Park",
    "Massena",
    "Middletown",
    "Mineola",
    "Mount Kisco",
    "Mount Vernon",
    "New Hyde Park",
    "New Rochelle",
    "New Square",
    "New York City",
    "Newark",
    "Newburgh",
    "Niagara Falls",
    "North Tonawanda",
    "Ogdensburg",
    "Olean",
    "Oneida",
    "Oneonta",
    "Ossining",
    "Oswego",
    "Patchogue",
    "Peekskill",
    "Plattsburgh",
    "Port Chester",
    "Potsdam",
    "Poughkeepsie",
    "Rensselaer",
    "Rochester",
    "Rockville Centre",
    "Rome",
    "Rye",
    "Rye Brook",
    "Saratoga Springs",
    "Scarsdale",
    "Schenectady",
    "Sleepy Hollow",
    "Spring Valley",
    "Suffern",
    "Syracuse",
    "Tarrytown",
    "Tonawanda",
    "Troy",
    "Utica",
    "Valley Stream",
    "Watertown",
    "Watervliet",
    "West Haverstraw",
    "Westbury",
    "White Plains",
    "Woodbury",
    "Yonkers",
  ],
  "North Carolina": [
    "Albemarle",
    "Apex",
    "Archdale",
    "Asheboro",
    "Asheville",
    "Belmont",
    "Boone",
    "Burlington",
    "Carrboro",
    "Cary",
    "Chapel Hill",
    "Charlotte",
    "Clayton",
    "Clemmons",
    "Clinton",
    "Concord",
    "Conover",
    "Cornelius",
    "Davidson",
    "Dunn",
    "Durham",
    "Eden",
    "Elizabeth City",
    "Elon",
    "Fayetteville",
    "Fletcher",
    "Fuquay-varina",
    "Garner",
    "Gastonia",
    "Goldsboro",
    "Graham",
    "Greensboro",
    "Greenville",
    "Harrisburg",
    "Havelock",
    "Henderson",
    "Hendersonville",
    "Hickory",
    "High Point",
    "Holly Springs",
    "Hope Mills",
    "Huntersville",
    "Indian Trail",
    "Jacksonville",
    "Kannapolis",
    "Kernersville",
    "Kings Mountain",
    "Kinston",
    "Knightdale",
    "Laurinburg",
    "Leland",
    "Lenoir",
    "Lewisville",
    "Lexington",
    "Lincolnton",
    "Lumberton",
    "Matthews",
    "Mebane",
    "Mint Hill",
    "Monroe",
    "Mooresville",
    "Morehead City",
    "Morganton",
    "Morrisville",
    "Mount Airy",
    "Mount Holly",
    "New Bern",
    "Newton",
    "Oak Island",
    "Oxford",
    "Pinehurst",
    "Pineville",
    "Raleigh",
    "Reidsville",
    "Roanoke Rapids",
    "Rockingham",
    "Rocky Mount",
    "Rolesville",
    "Salisbury",
    "Sanford",
    "Shelby",
    "Smithfield",
    "Southern Pines",
    "Spring Lake",
    "Stallings",
    "Statesville",
    "Summerfield",
    "Tarboro",
    "Thomasville",
    "Wake Forest",
    "Washington",
    "Waxhaw",
    "Waynesville",
    "Weddington",
    "Wendell",
    "Wesley Chapel",
    "Wilmington",
    "Wilson",
    "Winston-salem City",
    "Winterville",
  ],
  "North Dakota": [
    "Argusville",
    "Ashley",
    "Beach",
    "Belfield",
    "Berthold",
    "Beulah",
    "Bismarck",
    "Bottineau",
    "Bowman",
    "Burlington",
    "Cando",
    "Carrington",
    "Casselton",
    "Cavalier",
    "Center",
    "Cooperstown",
    "Crosby",
    "Devils Lake",
    "Dickinson",
    "Drayton",
    "Dunseith",
    "Edgeley",
    "Elgin",
    "Ellendale",
    "Emerado",
    "Enderlin",
    "Fargo",
    "Fessenden",
    "Forman",
    "Garrison",
    "Glen Ullin",
    "Glenburn",
    "Grafton",
    "Grand Forks",
    "Gwinner",
    "Hankinson",
    "Harvey",
    "Harwood",
    "Hatton",
    "Hazen",
    "Hebron",
    "Hettinger",
    "Hillsboro",
    "Horace",
    "Jamestown",
    "Kenmare",
    "Killdeer",
    "Kindred",
    "Lakota",
    "Lamoure",
    "Langdon",
    "Larimore",
    "Leeds",
    "Lidgerwood",
    "Lincoln",
    "Linton",
    "Lisbon",
    "Mandan",
    "Mapleton",
    "Mayville",
    "Milnor",
    "Minot",
    "Minto",
    "Mohall",
    "Mott",
    "Napoleon",
    "New",
    "New England",
    "New Rockford",
    "New Salem",
    "Northwood",
    "Oakes",
    "Park River",
    "Parshall",
    "Pembina",
    "Portland",
    "Ray",
    "Reile's Acres",
    "Richardton",
    "Rolette",
    "Rolla",
    "Rugby",
    "Stanley",
    "Steele",
    "Surrey",
    "Thompson",
    "Tioga",
    "Towner",
    "Turtle Lake",
    "Underwood",
    "Valley City",
    "Velva",
    "Wahpeton",
    "Walhalla",
    "Washburn",
    "Watford City",
    "West Fargo",
    "Williston",
    "Wilton",
    "Wishek",
  ],
  Ohio: [
    "Akron",
    "Alliance",
    "Ashland",
    "Athens",
    "Avon",
    "Avon Lake",
    "Barberton",
    "Beavercreek",
    "Berea",
    "Bowling Green",
    "Broadview Heights",
    "Brook Park",
    "Brunswick",
    "Canton",
    "Centerville",
    "Chillicothe",
    "Cincinnati",
    "Cleveland",
    "Cleveland Heights",
    "Columbus",
    "Cuyahoga Falls",
    "Dayton",
    "Delaware",
    "Dublin",
    "Eastlake",
    "Elyria",
    "Euclid",
    "Fairborn",
    "Fairfield",
    "Findlay",
    "Forest Park",
    "Gahanna",
    "Garfield Heights",
    "Green",
    "Grove City",
    "Hamilton",
    "Hilliard",
    "Huber Heights",
    "Hudson",
    "Kent",
    "Kettering",
    "Lakewood",
    "Lancaster",
    "Lebanon",
    "Lima",
    "Lorain",
    "Mansfield",
    "Maple Heights",
    "Marion",
    "Marysville",
    "Mason",
    "Massillon",
    "Mayfield Heights",
    "Medina",
    "Mentor",
    "Miamisburg",
    "Middletown",
    "Newark",
    "Niles",
    "North Olmsted",
    "North Ridgeville",
    "North Royalton",
    "Norwood",
    "Oregon",
    "Oxford",
    "Painesville",
    "Parma",
    "Parma Heights",
    "Perrysburg",
    "Pickerington",
    "Piqua",
    "Portsmouth",
    "Reynoldsburg",
    "Riverside",
    "Rocky River",
    "Sandusky",
    "Shaker Heights",
    "Sidney",
    "Solon",
    "South Euclid",
    "Springboro",
    "Springfield",
    "Stow",
    "Strongsville",
    "Sylvania",
    "Toledo",
    "Trotwood",
    "Troy",
    "Twinsburg",
    "Upper Arlington",
    "Wadsworth",
    "Warren",
    "Westerville",
    "Westlake",
    "Whitehall",
    "Willoughby",
    "Wooster",
    "Xenia",
    "Youngstown",
    "Zanesville",
  ],
  Oklahoma: [
    "Ada",
    "Altus",
    "Alva",
    "Anadarko",
    "Ardmore",
    "Bartlesville",
    "Bethany",
    "Bixby",
    "Blackwell",
    "Blanchard",
    "Bristow",
    "Broken Arrow",
    "Broken Bow",
    "Catoosa",
    "Chickasha",
    "Choctaw",
    "Claremore",
    "Clinton",
    "Collinsville",
    "Coweta",
    "Cushing",
    "Del City",
    "Dewey",
    "Duncan",
    "Durant",
    "Edmond",
    "El Reno",
    "Elk City",
    "Enid",
    "Fort Gibson",
    "Frederick",
    "Glenpool",
    "Grove",
    "Guthrie",
    "Guymon",
    "Harrah",
    "Heavener",
    "Henryetta",
    "Hobart",
    "Holdenville",
    "Hominy",
    "Hugo",
    "Idabel",
    "Jenks",
    "Kingfisher",
    "Lawton",
    "Lone Grove",
    "Madill",
    "Marlow",
    "Mcalester",
    "Mcloud",
    "Miami",
    "Midwest City",
    "Moore",
    "Muldrow",
    "Muskogee",
    "Mustang",
    "Newcastle",
    "Nichols Hills",
    "Noble",
    "Norman",
    "Nowata",
    "Oklahoma City City",
    "Okmulgee",
    "Owasso",
    "Pauls Valley",
    "Pawhuska",
    "Perry",
    "Piedmont",
    "Pocola",
    "Ponca City",
    "Poteau",
    "Pryor Creek",
    "Purcell",
    "Roland",
    "Sallisaw",
    "Sand Springs",
    "Sapulpa",
    "Sayre",
    "Seminole",
    "Shawnee",
    "Skiatook",
    "Slaughterville",
    "Spencer",
    "Stillwater",
    "Stilwell",
    "Sulphur",
    "Tahlequah",
    "Tecumseh",
    "The",
    "Tulsa",
    "Tuttle",
    "Verdigris",
    "Vinita",
    "Wagoner",
    "Warr Acres",
    "Weatherford",
    "Wewoka",
    "Woodward",
    "Yukon",
  ],
  Oregon: [
    "Albany",
    "Ashland",
    "Astoria",
    "Aumsville",
    "Baker City",
    "Bandon",
    "Beaverton",
    "Bend",
    "Boardman",
    "Brookings",
    "Burns",
    "Canby",
    "Central Point",
    "Coos Bay",
    "Coquille",
    "Cornelius",
    "Corvallis",
    "Cottage Grove",
    "Creswell",
    "Dallas",
    "Dundee",
    "Eagle Point",
    "Estacada",
    "Eugene",
    "Fairview",
    "Florence",
    "Forest Grove",
    "Gladstone",
    "Grants Pass",
    "Gresham",
    "Happy Valley",
    "Harrisburg",
    "Hermiston",
    "Hillsboro",
    "Hood River",
    "Hubbard",
    "Independence",
    "Jacksonville",
    "Jefferson City",
    "Junction City",
    "Keizer",
    "King City",
    "Klamath Falls",
    "La Grande",
    "Lafayette",
    "Lake Oswego",
    "Lebanon",
    "Lincoln City",
    "Madras",
    "Mcminnville",
    "Medford",
    "Milton-freewater",
    "Milwaukie",
    "Molalla",
    "Monmouth",
    "Mount Angel",
    "Myrtle Creek",
    "Newberg",
    "Newport",
    "North Bend",
    "Nyssa",
    "Oakridge",
    "Ontario",
    "Oregon City",
    "Pendleton",
    "Philomath",
    "Phoenix",
    "Portland",
    "Prineville",
    "Redmond",
    "Reedsport",
    "Roseburg",
    "Salem",
    "Sandy",
    "Scappoose",
    "Seaside",
    "Shady Cove",
    "Sheridan",
    "Sherwood",
    "Silverton",
    "Springfield",
    "St. Helens",
    "Stayton",
    "Sutherlin",
    "Sweet Home",
    "Talent",
    "The Dalles",
    "Tigard",
    "Tillamook",
    "Toledo",
    "Troutdale",
    "Tualatin",
    "Umatilla",
    "Veneta",
    "Warrenton",
    "West Linn",
    "Wilsonville",
    "Winston",
    "Wood",
    "Woodburn",
  ],
  Pennsylvania: [
    "Aliquippa",
    "Allentown",
    "Altoona",
    "Baldwin",
    "Beaver Falls",
    "Bellevue",
    "Berwick",
    "Bethel Park",
    "Bethlehem",
    "Bloomsburg",
    "Bradford",
    "Brentwood",
    "Bristol",
    "Brookhaven",
    "Butler",
    "Canonsburg",
    "Carbondale",
    "Carlisle",
    "Castle Shannon",
    "Chambersburg",
    "Chester",
    "Coatesville",
    "Collingdale",
    "Columbia",
    "Conshohocken",
    "Darby",
    "Dormont",
    "Doylestown",
    "Dunmore",
    "East Stroudsburg",
    "Easton",
    "Economy",
    "Elizabethtown",
    "Emmaus",
    "Ephrata",
    "Erie",
    "Franklin Park",
    "Greensburg",
    "Hanover",
    "Harrisburg",
    "Hazleton",
    "Hermitage",
    "Indiana",
    "Jeannette",
    "Jefferson Hills",
    "Johnstown",
    "Kingston",
    "Lancaster",
    "Lansdale",
    "Lansdowne",
    "Lebanon",
    "Lewistown",
    "Lititz",
    "Lock Haven",
    "Lower Burrell",
    "Mckeesport",
    "Meadville",
    "Mechanicsburg",
    "Middletown",
    "Millersville",
    "Monroeville",
    "Morrisville",
    "Mount Joy",
    "Munhall",
    "Murrysville",
    "Nanticoke",
    "New Castle",
    "New Kensington",
    "Norristown",
    "Northampton",
    "Oil City",
    "Perkasie",
    "Philadelphia",
    "Phoenixville",
    "Pittsburgh",
    "Pleasant Hills",
    "Plum",
    "Pottstown",
    "Pottsville",
    "Quakertown",
    "Reading",
    "Scranton",
    "Sharon",
    "St. Marys",
    "State College",
    "Sunbury",
    "Swissvale",
    "Uniontown",
    "Warren",
    "Washington",
    "Waynesboro",
    "West Chester",
    "West Mifflin",
    "Whitehall",
    "Wilkes-barre",
    "Wilkinsburg",
    "Williamsport",
    "Wyomissing",
    "Yeadon",
    "York",
  ],
  "Rhode Island": [
    "Central Falls",
    "Cranston",
    "East Providence",
    "Newport",
    "Pawtucket",
    "Providence",
    "Warwick",
    "Woonsocket",
  ],
  "South Carolina": [
    "Abbeville",
    "Aiken",
    "Allendale",
    "Anderson",
    "Andrews",
    "Bamberg",
    "Barnwell",
    "Batesburg-leesville",
    "Beaufort",
    "Belton",
    "Bennettsville",
    "Bishopville",
    "Bluffton",
    "Blythewood",
    "Burnettown",
    "Camden",
    "Cayce",
    "Central",
    "Charleston",
    "Cheraw",
    "Chester",
    "Clemson",
    "Clinton",
    "Clover",
    "Columbia",
    "Conway",
    "Darlington",
    "Denmark",
    "Dillon",
    "Duncan",
    "Easley",
    "Edgefield",
    "Florence",
    "Folly Beach",
    "Forest Acres",
    "Fort Mill",
    "Fountain Inn",
    "Gaffney",
    "Georgetown",
    "Goose Creek",
    "Greenville",
    "Greenwood",
    "Greer",
    "Hanahan",
    "Hardeeville",
    "Hartsville",
    "Hilton Head Island",
    "Hollywood",
    "Honea Path",
    "Irmo",
    "Isle Of Palms",
    "James Island",
    "Kingstree",
    "Lake City",
    "Lancaster",
    "Landrum",
    "Laurens",
    "Lexington",
    "Liberty",
    "Loris",
    "Lyman",
    "Manning",
    "Marion",
    "Mauldin",
    "Moncks Corner",
    "Mount Pleasant",
    "Mullins",
    "Myrtle Beach",
    "Newberry",
    "North Augusta",
    "North Charleston",
    "North Myrtle Beach",
    "Orangeburg",
    "Pageland",
    "Pendleton",
    "Pickens",
    "Port Royal",
    "Ravenel",
    "Ridgeland",
    "Rock Hill",
    "Saluda",
    "Seneca",
    "Simpsonville",
    "Spartanburg",
    "Springdale",
    "Summerville",
    "Sumter",
    "Surfside Beach",
    "Tega Cay",
    "Travelers Rest",
    "Union",
    "Walhalla",
    "Walterboro",
    "Wellford",
    "West Columbia",
    "Williamston",
    "Williston",
    "Winnsboro",
    "Woodruff",
    "York",
  ],
  "South Dakota": [
    "Aberdeen",
    "Alcester",
    "Alexandria",
    "Arlington",
    "Armour",
    "Aurora",
    "Baltic",
    "Belle Fourche",
    "Beresford",
    "Box Elder",
    "Brandon",
    "Britton",
    "Brookings",
    "Canistota",
    "Canton",
    "Castlewood",
    "Centerville",
    "Chamberlain",
    "Clark",
    "Clear Lake",
    "Colton",
    "Crooks",
    "Custer",
    "De Smet",
    "Deadwood",
    "Dell Rapids",
    "Eagle Butte",
    "Edgemont",
    "Elk Point",
    "Elkton",
    "Estelline",
    "Eureka",
    "Faulkton",
    "Flandreau",
    "Fort Pierre",
    "Freeman",
    "Garretson",
    "Gettysburg",
    "Gregory",
    "Groton",
    "Harrisburg",
    "Hartford",
    "Highmore",
    "Hill City",
    "Hot Springs",
    "Howard",
    "Huron",
    "Ipswich",
    "Kadoka",
    "Kimball",
    "Lake Andes",
    "Lead",
    "Lemmon",
    "Lennox",
    "Madison",
    "Marion",
    "Martin",
    "Mclaughlin",
    "Milbank",
    "Miller",
    "Mission",
    "Mitchell",
    "Mobridge",
    "New Underwood",
    "North Sioux City",
    "Onida",
    "Parker",
    "Parkston",
    "Philip",
    "Piedmont",
    "Pierre",
    "Plankinton",
    "Platte",
    "Rapid City City",
    "Redfield",
    "Salem",
    "Scotland",
    "Selby",
    "Sioux Falls City",
    "Sisseton",
    "Spearfish",
    "Springfield",
    "Sturgis",
    "Summerset",
    "Tea",
    "Tyndall",
    "Valley Springs",
    "Vermillion",
    "Viborg",
    "Volga",
    "Wagner",
    "Wall",
    "Watertown",
    "Webster",
    "Wessington Springs",
    "Whitewood",
    "Winner",
    "Woonsocket",
    "Worthing",
    "Yankton",
  ],
  Tennessee: [
    "Alcoa",
    "Arlington",
    "Athens",
    "Atoka",
    "Bartlett",
    "Brentwood",
    "Bristol",
    "Brownsville",
    "Chattanooga",
    "Church Hill",
    "Clarksville",
    "Cleveland",
    "Clinton",
    "Collegedale",
    "Collierville",
    "Columbia",
    "Cookeville",
    "Covington",
    "Crossville",
    "Dayton",
    "Dickson",
    "Dunlap",
    "Dyersburg",
    "East Ridge",
    "Elizabethton",
    "Erwin",
    "Fairview",
    "Farragut",
    "Fayetteville",
    "Franklin",
    "Gallatin",
    "Germantown",
    "Goodlettsville",
    "Greenbrier",
    "Greeneville",
    "Harriman",
    "Hartsville/trousdale",
    "Henderson",
    "Hendersonville",
    "Humboldt",
    "Jackson",
    "Jefferson City City",
    "Johnson City",
    "Jonesborough",
    "Kingsport",
    "Kingston",
    "Knoxville",
    "La Follette",
    "La Vergne",
    "Lafayette",
    "Lakeland",
    "Lawrenceburg",
    "Lebanon",
    "Lenoir City",
    "Lewisburg",
    "Lexington",
    "Loudon",
    "Lynchburg",
    "Madisonville",
    "Manchester",
    "Martin",
    "Maryville",
    "Mckenzie",
    "Mcminnville",
    "Memphis",
    "Milan",
    "Millersville",
    "Millington",
    "Morristown",
    "Mount Carmel",
    "Mount Juliet",
    "Munford",
    "Murfreesboro",
    "Nashville-davidson",
    "Newport",
    "Nolensville",
    "Oak Ridge",
    "Oakland",
    "Paris",
    "Pigeon Forge",
    "Portland",
    "Pulaski",
    "Red Bank",
    "Ripley",
    "Rockwood",
    "Savannah",
    "Sevierville",
    "Shelbyville",
    "Signal Mountain",
    "Smyrna",
    "Soddy-daisy",
    "Sparta",
    "Spring Hill",
    "Springfield",
    "Sweetwater",
    "Thompson's Station",
    "Tullahoma",
    "Union City",
    "White House",
    "Winchester",
  ],
  Texas: [
    "Abilene",
    "Allen",
    "Amarillo",
    "Arlington",
    "Austin",
    "Baytown",
    "Beaumont",
    "Bedford",
    "Brownsville",
    "Bryan",
    "Burleson",
    "Carrollton",
    "Cedar Hill",
    "Cedar Park",
    "College Station",
    "Conroe",
    "Coppell",
    "Copperas Cove",
    "Corpus Christi",
    "Dallas",
    "Deer Park",
    "Del Rio",
    "Denton",
    "Desoto",
    "Duncanville",
    "Edinburg",
    "El Paso",
    "Euless",
    "Farmers Branch",
    "Flower Mound",
    "Fort Worth",
    "Friendswood",
    "Frisco",
    "Galveston",
    "Garland",
    "Georgetown",
    "Grand Prairie",
    "Grapevine",
    "Haltom City",
    "Harlingen",
    "Houston",
    "Huntsville",
    "Hurst",
    "Irving",
    "Keller",
    "Killeen",
    "Kyle",
    "La Porte",
    "Lancaster",
    "Laredo",
    "League City",
    "Leander",
    "Lewisville",
    "Little Elm",
    "Longview",
    "Lubbock",
    "Lufkin",
    "Mansfield",
    "Mcallen",
    "Mckinney",
    "Mesquite",
    "Midland",
    "Midlothian",
    "Mission",
    "Missouri City",
    "Nacogdoches",
    "New Braunfels",
    "North Richland Hills",
    "Odessa",
    "Pasadena",
    "Pearland",
    "Pflugerville",
    "Pharr",
    "Plano",
    "Port Arthur",
    "Richardson",
    "Rockwall",
    "Rosenberg",
    "Round Rock",
    "Rowlett",
    "San Angelo",
    "San Antonio",
    "San Juan",
    "San Marcos",
    "Schertz",
    "Sherman",
    "Socorro",
    "Sugar Land",
    "Temple City",
    "Texarkana",
    "Texas City",
    "The Colony",
    "Tyler",
    "Victoria",
    "Waco",
    "Waxahachie",
    "Weatherford",
    "Weslaco",
    "Wichita Falls City",
    "Wylie",
  ],
  Utah: [
    "Alpine",
    "American Fork",
    "Blanding",
    "Bluffdale",
    "Bountiful",
    "Brigham City",
    "Cedar City",
    "Cedar Hills",
    "Centerville",
    "Clearfield",
    "Clinton",
    "Cottonwood Heights",
    "Draper",
    "Eagle Mountain",
    "Elk Ridge",
    "Enoch",
    "Ephraim",
    "Farmington",
    "Farr West",
    "Fruit Heights",
    "Grantsville",
    "Harrisville",
    "Heber",
    "Herriman",
    "Highland",
    "Holladay",
    "Hooper",
    "Hurricane",
    "Hyde Park",
    "Hyrum",
    "Ivins",
    "Kanab",
    "Kaysville",
    "Kearns",
    "La Verkin",
    "Layton",
    "Lehi",
    "Lindon",
    "Logan",
    "Magna",
    "Manti",
    "Mapleton",
    "Midvale",
    "Midway",
    "Millcreek",
    "Moab",
    "Morgan",
    "Murray",
    "Nephi",
    "Nibley",
    "North Logan",
    "North Ogden",
    "North Salt Lake",
    "Ogden",
    "Orem",
    "Park City",
    "Payson",
    "Perry",
    "Plain City",
    "Pleasant Grove",
    "Pleasant View",
    "Price",
    "Providence",
    "Provo",
    "Richfield",
    "Riverdale",
    "Riverton",
    "Roosevelt",
    "Roy",
    "Salem",
    "Salt Lake City City",
    "Sandy",
    "Santa Clara",
    "Santaquin",
    "Saratoga Springs",
    "Smithfield",
    "South Jordan",
    "South Ogden",
    "South Salt Lake",
    "South Weber",
    "Spanish Fork",
    "Springville",
    "St. George City",
    "Sunset",
    "Syracuse",
    "Taylorsville",
    "Tooele",
    "Tremonton",
    "Vernal",
    "Vineyard",
    "Washington",
    "Washington Terrace",
    "Wellsville",
    "West Bountiful",
    "West Haven",
    "West Jordan",
    "West Point",
    "West Valley City",
    "White",
    "Woods Cross",
  ],
  Vermont: [
    "Albany",
    "Alburgh",
    "Barre",
    "Barton",
    "Bellows Falls",
    "Burlington",
    "Cambridge",
    "Derby Center",
    "Derby Line",
    "Enosburg Falls",
    "Essex Junction",
    "Hyde Park",
    "Jacksonville",
    "Jeffersonville",
    "Johnson",
    "Ludlow",
    "Lyndonville",
    "Manchester",
    "Marshfield",
    "Montpelier",
    "Morrisville",
    "Newbury",
    "Newfane",
    "Newport",
    "North Bennington",
    "North Troy",
    "Old Bennington",
    "Orleans",
    "Perkinsville",
    "Poultney",
    "Rutland",
    "Saxtons River",
    "South Burlington",
    "St. Albans",
    "Swanton",
    "Vergennes",
    "Wells River",
    "West Burke",
    "Westminster",
    "Winooski",
    "Woodstock",
  ],
  Virginia: [
    "Abingdon",
    "Alexandria",
    "Altavista",
    "Amherst",
    "Ashland",
    "Bedford",
    "Berryville",
    "Big Stone Gap",
    "Blacksburg",
    "Blackstone",
    "Bluefield",
    "Bridgewater",
    "Bristol",
    "Broadway",
    "Buena Vista",
    "Charlottesville",
    "Chase City",
    "Chesapeake",
    "Chincoteague",
    "Christiansburg",
    "Clifton Forge",
    "Coeburn",
    "Colonial Beach",
    "Colonial Heights",
    "Covington",
    "Crewe",
    "Culpeper",
    "Danville",
    "Dublin",
    "Dumfries",
    "Elkton",
    "Emporia",
    "Fairfax",
    "Falls Church",
    "Farmville",
    "Franklin",
    "Fredericksburg",
    "Front Royal",
    "Galax",
    "Gate City",
    "Grottoes",
    "Hampton",
    "Harrisonburg",
    "Herndon",
    "Hillsville",
    "Hopewell",
    "Lebanon",
    "Leesburg",
    "Lexington",
    "Lovettsville",
    "Luray",
    "Lynchburg",
    "Manassas",
    "Manassas Park",
    "Marion",
    "Martinsville",
    "Mount Jackson",
    "Narrows",
    "New Market",
    "Newport News",
    "Norfolk",
    "Norton",
    "Orange",
    "Pearisburg",
    "Petersburg",
    "Poquoson",
    "Portsmouth",
    "Pulaski",
    "Purcellville",
    "Radford",
    "Richlands",
    "Richmond",
    "Roanoke",
    "Rocky Mount",
    "Salem",
    "Saltville",
    "Shenandoah",
    "Smithfield",
    "South Boston",
    "South Hill",
    "Staunton",
    "Stephens City",
    "Strasburg",
    "Suffolk",
    "Tappahannock",
    "Tazewell",
    "Timberville",
    "Vienna",
    "Vinton",
    "Virginia Beach",
    "Warrenton",
    "Waverly",
    "Waynesboro",
    "West Point",
    "Williamsburg",
    "Winchester",
    "Windsor",
    "Wise",
    "Woodstock",
    "Wytheville",
  ],
  Washington: [
    "Aberdeen",
    "Airway Heights",
    "Anacortes",
    "Arlington",
    "Auburn",
    "Bainbridge Island",
    "Battle Ground",
    "Bellevue",
    "Bellingham",
    "Bonney Lake",
    "Bothell",
    "Bremerton",
    "Burien",
    "Burlington",
    "Camas",
    "Centralia",
    "Cheney",
    "College Place",
    "Covington",
    "Des Moines City",
    "Dupont",
    "Duvall",
    "East Wenatchee",
    "Edgewood",
    "Edmonds",
    "Ellensburg",
    "Enumclaw",
    "Ephrata",
    "Everett",
    "Federal Way",
    "Ferndale",
    "Fife",
    "Gig Harbor",
    "Grandview",
    "Hoquiam",
    "Issaquah",
    "Kelso",
    "Kenmore",
    "Kennewick",
    "Kent",
    "Kirkland",
    "Lacey",
    "Lake Forest Park",
    "Lake Stevens",
    "Lakewood",
    "Liberty Lake",
    "Longview",
    "Lynden",
    "Lynnwood",
    "Maple Valley",
    "Marysville",
    "Mercer Island",
    "Mill Creek",
    "Milton",
    "Monroe",
    "Moses Lake",
    "Mount Vernon",
    "Mountlake Terrace",
    "Mukilteo",
    "Newcastle",
    "Oak Harbor",
    "Olympia",
    "Orting",
    "Othello",
    "Pasco",
    "Port Angeles",
    "Port Orchard",
    "Port Townsend",
    "Poulsbo",
    "Pullman",
    "Puyallup",
    "Redmond",
    "Renton",
    "Richland",
    "Ridgefield",
    "Sammamish",
    "Seatac",
    "Seattle",
    "Sedro-woolley",
    "Shelton",
    "Shoreline",
    "Snohomish",
    "Snoqualmie",
    "Spokane",
    "Spokane Valley",
    "Sumner",
    "Sunnyside",
    "Tacoma",
    "Toppenish",
    "Tukwila",
    "Tumwater",
    "University Place",
    "Vancouver",
    "Walla Walla",
    "Washougal",
    "Wenatchee",
    "West Richland",
    "Woodinville",
    "Yakima",
    "Yelm",
  ],
  "West Virginia": [
    "Alderson",
    "Ansted",
    "Barboursville",
    "Barrackville",
    "Beckley",
    "Belington",
    "Belle",
    "Benwood",
    "Bethlehem",
    "Bluefield",
    "Bridgeport",
    "Buckhannon",
    "Buffalo",
    "Ceredo",
    "Charles",
    "Charleston",
    "Chesapeake",
    "Chester",
    "Clarksburg",
    "Clendenin",
    "Dunbar",
    "Eleanor",
    "Elkins",
    "Fairmont",
    "Fayetteville",
    "Follansbee",
    "Glen Dale",
    "Glenville",
    "Grafton",
    "Granville",
    "Harrisville",
    "Hinton",
    "Huntington",
    "Hurricane",
    "Kenova",
    "Keyser",
    "Kingwood",
    "Lewisburg",
    "Logan",
    "Mabscott",
    "Madison",
    "Mannington",
    "Marmet",
    "Martinsburg",
    "Mcmechen",
    "Milton",
    "Monongah",
    "Montgomery",
    "Moorefield",
    "Morgantown",
    "Moundsville",
    "Mount Hope",
    "Mullens",
    "New Haven",
    "New Martinsville",
    "Nitro",
    "Nutter Fort",
    "Oak Hill",
    "Oceana",
    "Paden City",
    "Parkersburg",
    "Parsons",
    "Petersburg",
    "Philippi",
    "Pleasant Valley",
    "Point Pleasant",
    "Princeton",
    "Rainelle",
    "Ranson Corporation",
    "Ravenswood",
    "Richwood",
    "Ripley",
    "Romney",
    "Ronceverte",
    "Salem",
    "Shepherdstown",
    "Shinnston",
    "Sistersville",
    "Sophia",
    "South Charleston",
    "Spencer",
    "St. Albans",
    "St. Marys",
    "Star City",
    "Stonewood",
    "Summersville",
    "Terra Alta",
    "Vienna",
    "Wayne",
    "Weirton",
    "Welch",
    "Wellsburg",
    "West Liberty",
    "Weston",
    "Westover",
    "Wheeling",
    "White Sulphur Springs",
    "Williamson",
    "Williamstown",
    "Winfield",
  ],
  Wisconsin: [
    "Allouez",
    "Appleton",
    "Ashwaubenon",
    "Baraboo",
    "Beaver Dam",
    "Bellevue",
    "Beloit",
    "Brookfield",
    "Brown Deer",
    "Burlington",
    "Caledonia",
    "Cedarburg",
    "Chippewa Falls City",
    "Cudahy",
    "De Pere",
    "Deforest",
    "Eau Claire",
    "Elkhorn",
    "Fitchburg",
    "Fond Du Lac",
    "Fort Atkinson",
    "Fox Crossing",
    "Franklin",
    "Germantown",
    "Glendale",
    "Grafton",
    "Green Bay",
    "Greendale",
    "Greenfield",
    "Harrison",
    "Hartford",
    "Hartland",
    "Hobart",
    "Holmen",
    "Howard",
    "Hudson",
    "Janesville",
    "Kaukauna",
    "Kenosha",
    "La Crosse",
    "Little Chute",
    "Madison",
    "Manitowoc",
    "Marinette",
    "Marshfield",
    "Menasha",
    "Menomonee Falls",
    "Menomonie",
    "Mequon",
    "Merrill",
    "Middleton",
    "Milwaukee",
    "Monroe",
    "Mount Pleasant",
    "Muskego",
    "Neenah",
    "New Berlin",
    "New Richmond",
    "Oak Creek",
    "Oconomowoc",
    "Onalaska",
    "Oregon",
    "Oshkosh",
    "Pewaukee",
    "Platteville",
    "Pleasant Prairie",
    "Plover",
    "Port Washington",
    "Portage",
    "Racine",
    "Reedsburg",
    "Richfield",
    "River Falls City",
    "Salem Lakes",
    "Sheboygan",
    "Shorewood",
    "South Milwaukee",
    "Sparta",
    "St. Francis",
    "Stevens Point",
    "Stoughton",
    "Suamico",
    "Sun Prairie",
    "Superior",
    "Sussex",
    "Tomah",
    "Two Rivers",
    "Verona",
    "Watertown",
    "Waukesha",
    "Waunakee",
    "Waupun",
    "Wausau",
    "Wauwatosa",
    "West Allis",
    "West Bend",
    "Weston",
    "Whitefish Bay",
    "Whitewater",
    "Wisconsin Rapids",
  ],
  Wyoming: [
    "Afton",
    "Albin",
    "Alpine",
    "Baggs",
    "Bairoil",
    "Bar Nunn",
    "Basin",
    "Bear River",
    "Big Piney",
    "Buffalo",
    "Burlington",
    "Burns",
    "Byron",
    "Casper",
    "Cheyenne",
    "Chugwater",
    "Clearmont",
    "Cody",
    "Cokeville",
    "Cowley",
    "Dayton",
    "Deaver",
    "Diamondville",
    "Dixon",
    "Douglas",
    "Dubois",
    "East Thermopolis",
    "Edgerton",
    "Elk Mountain",
    "Encampment",
    "Evanston",
    "Evansville",
    "Fort Laramie",
    "Frannie",
    "Gillette",
    "Glendo",
    "Glenrock",
    "Granger",
    "Green River",
    "Greybull",
    "Guernsey",
    "Hanna",
    "Hartville",
    "Hudson",
    "Hulett",
    "Jackson",
    "Kaycee",
    "Kemmerer",
    "Kirby",
    "La Barge",
    "La Grange",
    "Lander",
    "Laramie",
    "Lingle",
    "Lost Springs",
    "Lovell",
    "Lusk",
    "Lyman",
    "Manderson",
    "Manville",
    "Marbleton",
    "Medicine Bow",
    "Meeteetse",
    "Midwest",
    "Mills",
    "Moorcroft",
    "Mountain View",
    "Newcastle",
    "Opal",
    "Pavillion",
    "Pine Bluffs",
    "Pine Haven",
    "Pinedale",
    "Powell",
    "Ranchester",
    "Rawlins",
    "Riverside",
    "Riverton",
    "Rock River",
    "Rock Springs",
    "Rolling Hills",
    "Saratoga",
    "Sheridan",
    "Shoshoni",
    "Sinclair",
    "Star Valley Ranch",
    "Sundance",
    "Superior",
    "Ten Sleep",
    "Thayne",
    "Thermopolis",
    "Torrington",
    "Upton",
    "Van Tassell",
    "Wamsutter",
    "Wheatland",
    "Worland",
    "Wright",
    "Yoder",
  ],
};
