export const CURRENT_VERSION = "0.7.22";

export interface VersionEntry {
  version: string;
  date: string;
  title: string;
  changes: string[];
}

export const CHANGELOG: VersionEntry[] = [
  {
    version: "0.7.22",
    date: "2026-05-19",
    title: "Landing Page templates — auditoría completa, los 9 rewritten con fidelidad real a la marca inspirante",
    changes: [
      "Los 9 templates inspirados en marcas externas reescritos a fondo para que se vean como secciones reales de los sitios originales (Apple, Stripe, Linear, Airbnb, Notion, Tesla, Best Buy, Spotify, HubSpot)",
      "Apple Minimal: SF Pro, frosted nav rgba(.72)+blur, pill CTAs apple.com style (border-radius:980px), alternando #fff/#f5f5f7, multi-column footer Apple-style — el user reportó que veía 'fondo oscuro' (era el iframe parent), confirmado en preview: bg ahora #fff puro",
      "Stripe: gradient mesh animado real (4 radial-circles purple/cyan/pink/mint con drift 18s), code-preview block en How It Works, navy footer, todo en Sohne/Inter",
      "Linear: signature grid pattern de 64x64 + purple glow centrado, sharp 6px CTAs (NO pills), Inter Display, cards con border-hover violet — el aesthetic exacto de linear.app",
      "Airbnb: search-pill nav real + booking-card hero con coral #FF385C exacto (gradient con #E61E4D), category strip horizontal, rounded-32 cards, multi-column footer con 'English (US) · $ USD' toggles",
      "Spotify: pitch black + #1ed760 (green nuevo, no el legacy #1DB954), Spotify-circular-style logo SVG, hero con triple album-art rotado, big pill CTA con hover:scale(1.04), 'CLIPBOARD' card surfaces #181818",
      "Tesla: nav transparente que se vuelve sólido on-scroll (window.scrollY>40), Gotham condensed uppercase weight 500, full-bleed 100vh hero dark, dual CTAs (blue+outline) border-radius:4px, sections white #fff con padding 120px+",
      "Notion: PURO blanco #fff (no off-white), Lyon serif para headings, soft blocks con border:1px solid #ebebeb, mock document hero con browser-chrome + welcome H1 serif, black footer",
      "Best Buy: top utility bar dark, blue #0046BE nav, yellow #FFE000 ribbon 'FREE shipping over $35', deal cards con corner-badge DEAL + strike-through red #C9242D, dark #1d252c footer",
      "HubSpot: orange #FF7A59 dominante (nav CTA pill, submit pill, FAQ +/- toggle, gradient band), 6 grayscale Fortune-500 logo placeholders, Lexend Deca, navy footer #33475b",
      "Mantenidos los 58 placeholders y el form schema en los 10 templates — cero breaking changes downstream",
    ],
  },
  {
    version: "0.7.21",
    date: "2026-05-19",
    title: "Landing Pages — prompts bilingües (15 verticales), generación language-aware, defensive bg fix",
    changes: [
      "PROMPT_TEMPLATES en Create Landing Page ahora son bilingües: labels y prompts vienen del diccionario i18n (lp_prompts.*), por lo que respetan EN/ES seleccionado",
      "Expandidos de 4 a 15 verticales: Restaurant, Clinic, Gym, Spa (existentes mejorados) + Auto Repair, Law Firm, Real Estate, HVAC/Plumber, Photography, Tutoring, Pet/Vet, Cleaning, Auto Dealer, Consulting, E-commerce — cada uno con prompt copywriting-grade que menciona features específicos de Eko AI",
      "Backend SYSTEM_PROMPT (landing_page_template.py) ya NO hardcodea inglés: el AI auto-detecta el idioma del prompt y genera TODO el copy en ese idioma, manteniendo brand names (Eko AI, Cal.com, VAPI) y siglas técnicas (CRM, SEO) en inglés",
      "Defensive fix visual: agregado `html{background:var(--bg);min-height:100vh}` + `body{...;min-height:100vh}` a los 10 templates para que el bg del LP cubra todo el viewport y no haya leak del parent (iframe/preview) en el área debajo del contenido",
      "Resultado: usuario español ve botones 'Restaurante / Clínica / etc.' con prompts en español → LP generada en español; usuario inglés ve 'Restaurant / Clinic / etc.' con prompts en inglés → LP en inglés",
    ],
  },
  {
    version: "0.7.20",
    date: "2026-05-19",
    title: "i18n cobertura completa — 14 páginas internas traducidas (568 nuevas keys EN/ES)",
    changes: [
      "Las 14 páginas que en v0.7.19 quedaron con texto hardcoded en español ahora están totalmente traducidas: leads, pipeline, deals, proposals, voice-agent, content-studio, inbox, sequences, campaigns, calendar, analytics, landing-pages, settings, billing",
      "568 nuevas keys agregadas al diccionario (en/es), namespaced por página (leads.*, inbox.*, landing.*, deals.*, proposals.*, voice.*, content.*, sequences.*, campaigns.*, calendar.*, analytics.*, settings.*, billing.*) — 1356 entries totales en translations.ts",
      "Delegación a 3 agentes en paralelo (~15 min total) — cada uno con un namespace propio para evitar collisions; merge automático con script Python (cero collisions encontradas)",
      "Cero regresiones: las 15 rutas (/, /leads, /pipeline, /deals, /proposals, /voice-agent, /content-studio, /inbox, /sequences, /campaigns, /calendar, /analytics, /landing-pages, /settings, /billing) responden HTTP 200 después del deploy",
      "Brand names preservados en ambos idiomas (Eko AI, VAPI, Stripe, Resend, Coinbase, Kimi, MiniMax, etc.) y terms técnicos comunes en español tech (Inbox, Lead, Deal, Pipeline, Score, Workspace) también preservados intencionalmente",
      "Cobertura total ahora: Navbar + Dashboard + ModulesGrid + RecentLeads + DiscoveryForm (v0.7.19) + las 14 páginas (v0.7.20) = cada rincón visible de Eko AI cambia al instante con el selector EN/ES",
    ],
  },
  {
    version: "0.7.19",
    date: "2026-05-19",
    title: "i18n — selector EN/ES + Dashboard, Navbar y componentes shared traducidos",
    changes: [
      "Nueva infraestructura i18n: I18nProvider (Context) + useT() hook + diccionarios EN/ES en lib/i18n/translations.ts",
      "LanguageSelector dropdown agregado al Navbar (icono Languages + bandera + código) — al cambiar idioma, TODO lo que usa useT() se traduce inmediatamente sin recargar",
      "Persistencia: localStorage key eko_lang_v1; auto-detect navigator.language (es → Spanish, todo lo demás → English por default)",
      "Traducidos: Navbar (todos los nav links primarios + dropdown Más + Objetos + Logout + System Online), Dashboard (header, subtitle, 4 StatCards, mensaje de discovery), ModulesGrid (header Módulos, Editar/Listo, Reset, hint, picker Agregar), RecentLeads (título, See all, empty state, score), DiscoveryForm (todos los labels + placeholders + búsqueda result messages), 14 cards de módulos (label + subtitle)",
      "Páginas individuales como /leads, /content-studio, /landing-pages, /pipeline, /settings etc. todavía tienen su texto en Spanish hardcoded — pendientes para próximos turnos pero la infraestructura está lista (basta importar useT y reemplazar strings)",
    ],
  },
  {
    version: "0.7.18",
    date: "2026-05-19",
    title: "Dashboard — agregados Landing Pages + Billing, orden lógico por funnel",
    changes: [
      "Faltaba Landing Pages en el grid de módulos del dashboard — agregado con icono LayoutTemplate (sky)",
      "Faltaba Billing (Stripe & plan) — agregado con icono CreditCard (amber)",
      "Reordenados los 14 módulos por flujo lógico del funnel: ACQUIRE (Leads, Landing Pages) → ENGAGE (Inbox, Sequences, Campaigns, Voice, Calendar) → CLOSE (Pipeline, Deals, Proposals) → GROW (Content, Analytics) → OPS (Billing, Config)",
      "Bump localStorage key v1 → v2 para que el nuevo default aplique en todos los browsers — los reorders custom previos se resetean (eran de la sesión del lanzamiento de drag-and-drop hoy mismo)",
      "La funcionalidad de drag-and-drop, jiggle edit mode y add/remove sigue intacta — el user puede re-customizar el nuevo orden",
    ],
  },
  {
    version: "0.7.17",
    date: "2026-05-19",
    title: "Dashboard — módulos reordenables + agregar/quitar (estilo macOS Tahoe)",
    changes: [
      "Nuevo componente ModulesGrid: drag-and-drop con @dnd-kit/sortable para reordenar los módulos del dashboard",
      "Botón 'Editar' arriba a la derecha entra en modo edit: las cards comienzan a hacer wiggle (jiggle) tipo widget de macOS Tahoe — keyframes alternados (-0.9deg / +0.7deg) en cards pares/impares",
      "En modo edit: click ✕ en la esquina superior izquierda quita el módulo · tile '+' al final del grid abre picker con módulos disponibles para re-agregar",
      "Persistencia en localStorage (eko_dashboard_modules_order_v1 y eko_dashboard_modules_hidden_v1) — el orden y los módulos visibles se mantienen por dispositivo/navegador",
      "Esc o botón 'Done' salen del modo edit · botón 'Reset' restaura orden y módulos originales · nuevos módulos del producto se agregan automáticamente al final si no estaban en la config guardada",
      "Modo normal (fuera de edit): comportamiento idéntico al anterior — cada card es Link que navega a su ruta",
    ],
  },
  {
    version: "0.7.16",
    date: "2026-05-19",
    title: "Dashboard — cards de Leads Recientes son clickeables completos",
    changes: [
      "Antes: solo el botón 'View Profile' navegaba al detalle del lead — clickear el body de la card no hacía nada",
      "Ahora: toda la card es un <Link> a /leads/{id} — click en cualquier parte (nombre, scores, badges, iconos) abre el perfil completo del lead",
      "Hover state mejorado: bg, border, business_name en azul + ArrowRight icon con slide animation",
    ],
  },
  {
    version: "0.7.15",
    date: "2026-05-19",
    title: "Email pipeline — circuit breaker para Resend daily_quota_exceeded",
    changes: [
      "Bug raíz descubierto: 3 leads de prueba (testeko@example.com, testuser123@example.com, checkmark@test.com) estaban en loop infinito en la nurture sequence — ~864 retry attempts/día agotaron toda la quota free-tier de Resend (100/día) → 1338 envíos fallidos / 0 exitosos",
      "Síntoma reportado por user: llenó form de Landing Page con su email + icapellis.com pero no le llegó el análisis AI (el lead 615 se enriqueció perfecto, score 73-80, pero send falló con daily_quota_exceeded)",
      "Hotfix: borrados los 3 leads de prueba → loop bajó de ~36 fails/5min a 2/5min (18x menos)",
      "Circuit breaker en backend/app/agents/outreach/channels/email.py: cuando Resend devuelve daily_quota_exceeded, se setea key Redis 'email:quota_exhausted:resend' con TTL hasta UTC midnight; las siguientes llamadas a send() short-circuitan inmediatamente sin pegarle a Resend",
      "Lead 615 (icapellis.com) reenvío programado vía 'at' job a 18:05 MDT (5min después del reset de quota Resend a 00:00 UTC)",
    ],
  },
  {
    version: "0.7.14",
    date: "2026-05-19",
    title: "Landing Pages — fix client-side crash en Save & Activate",
    changes: [
      "Fix crítico: 'Application error: a client-side exception has occurred' al clickear Save & Activate sin llenar name/slug — el backend devolvía 422 con detail=array-de-objects y React tiraba 'Objects are not valid as a React child' al renderizarlo",
      "Nuevo helper formatApiError() normaliza cualquier shape de error de FastAPI (string, array de validation errors, object) a un string legible — aplicado a las 9 llamadas setError() de la página",
      "Save Draft y Save & Activate ahora se deshabilitan cuando name o slug están vacíos — UX previene el 422 antes de llegar al backend",
      "Tooltip 'Name and slug are required' cuando los botones están disabled",
    ],
  },
  {
    version: "0.7.13",
    date: "2026-05-19",
    title: "Landing Pages — 10 templates con selector visual en Create modal",
    changes: [
      "Refactor backend: registry de templates en landing_page_template.py — 10 diseños distintos comparten el mismo placeholder schema (56 keys) para que una sola generación AI sirva en cualquier template",
      "10 templates inspirados en sitios icónicos: Eko Classic, Apple Minimal, Stripe Gradient, Linear Dark, Airbnb Warm, Notion Clean, Tesla Bold, Best Buy Retail, Spotify Vibe, HubSpot Sales",
      "Cada template usa colores + tipografía + layout fieles al original (SF Pro Apple, Inter Linear, Circular Spotify, Lyon Notion, Gotham Tesla, etc.)",
      "Nuevo endpoint GET /api/v1/landing-pages/templates — lista metadata de los 10 templates (sin HTML)",
      "Nuevo endpoint GET /api/v1/landing-pages/template-preview/{id} — renderiza un template con copy default (para iframe thumbnails en el selector)",
      "Schema LandingPageCreate y LandingPageGenerateRequest aceptan template_id opcional",
      "template_id se guarda en generation_metadata (jsonb existente, sin migración de DB)",
      "Frontend Create modal: nuevo grid de 10 cards con iframe-thumbnail (scale 0.15) — el usuario ve preview real de cada template antes de elegir",
      "AI Prompt sigue funcionando encima del template elegido — adjusta copy + content al niche",
      "End-to-end verificado: create LP con template=stripe-gradient → AI generation 51s → form submit → lead created (id 614)",
    ],
  },
  {
    version: "0.7.12",
    date: "2026-05-19",
    title: "Landing Pages — Active preview: línea blanca del scrollbar eliminada",
    changes: [
      "Fix: línea blanca vertical en el borde derecho del preview del card 'LANDING PAGE EN USO' era el scrollbar nativo del iframe (la LP es ~4000px, iframe a 800px)",
      "Solución: iframe width = VW + 24 (1304px), scale calculado con VW = 1280 — la scrollbar queda 5px fuera del container y overflow-hidden la clipa",
      "Bonus: colorScheme dark en el iframe — scrollbar dark en caso de Firefox/Safari donde el clipping no sea exacto",
    ],
  },
  {
    version: "0.7.11",
    date: "2026-05-19",
    title: "Landing Pages — Active card preview thumbnail rediseñado",
    changes: [
      "Fix: preview del card 'LANDING PAGE EN USO' tenía recuadro blanco visible (bg-white) y iframe scale fijo 0.15 que no rellenaba el container",
      "Nuevo componente <ActivePreview/> con scale dinámico vía ResizeObserver — el iframe llena 100% del ancho del card en cualquier viewport",
      "Aspect ratio 16:10 (en vez de h-24 = 96px fijo) — preview ahora ~175px alto en sidebar normal, se distinguen hero, form y benefits",
      "Background match con tema dark (#0F172A) — sin más rectángulo blanco contra el card azul-oscuro",
      "pointer-events-none en iframe para que clicks pasen al card (botones View/Edit/Deactivate intactos)",
      "loading=lazy en iframe para evitar fetch si el card está fuera de viewport",
    ],
  },
  {
    version: "0.7.10",
    date: "2026-05-18",
    title: "Landing Pages — Feature mentions en TODAS las secciones",
    changes: [
      "v0.7.9 introdujo Capability Library pero solo BENEFIT cards la usaban — REVIEWS, FAQs, FOOTER, HOW_IT_WORKS, HERO_SUBTITLE seguían sonando 'phone bot genérico'",
      "Coverage antes: 2-3/6 secciones con feature mentions; coverage después: 6/6 en las 4 niches",
      "Nuevo bloque 'PER-SECTION COPY RULES' obliga al AI a nombrar features en cada sección con ejemplos concretos",
      "Capability Library expandida con detalles granulares (FLUX, Ken Burns, karaoke subs DejaVu Sans, Buffer peak-hours, 4 escenas shorts/6 longs, end-frame CTA dinámico, Edge-TTS multilingüe, A/B Compare tab con 7 analytics columns)",
      "Reviews ahora mencionan wins específicos: '12 reels published, IG +40%', 'Lead Scoring flagged 8 at-risk, won 6 back', 'Voice Outbound called 40 dormant, 12 reactivated'",
      "FAQs incluyen 2 feature-education por página: 'Does Eko create content?', 'Can it predict churn?', 'Recall sequences?'",
      "FOOTERs ahora venden plataforma: 'Reception, Marketing, and Follow-up — Handled', 'Your Entire Patient Journey, Automated'",
      "Guardrail nuevo: 'If REVIEWS, FAQs, or FOOTER mention ZERO features by name, you have failed — rewrite'",
      "Niche-conservatism mantenida: Clínica Dental sigue sin Content Studio (compliance healthcare); usa Lead Scoring + Nurture",
    ],
  },
  {
    version: "0.7.9",
    date: "2026-05-18",
    title: "Landing Pages — Generator conoce el stack completo de Eko AI",
    changes: [
      "SYSTEM_PROMPT_TEMPLATE expandido con 'Capability Library' de 10 features de la plataforma",
      "Antes el AI solo vendía 'phone bot' — ahora rota benefits según el niche desde un pool de 10",
      "Nuevas features promocionadas: AI Social Content Studio (videos auto-publicados a IG/TikTok/YouTube/FB/LinkedIn), Self-Service Landing Page Builder (cliente crea sus propias páginas), AI Proposal Generator, Voice AI Outbound (VAPI), Smart CRM con Lead Scoring, AI Email Reply Agent, Nurture Sequences, Unified Inbox",
      "Guidelines explícitas en el prompt: 'A restaurant gets booking + WhatsApp + content + voice outbound. A spa gets content + booking + landing pages + multilingual receptionist.'",
      "4 LPs regeneradas (Restaurante/Clínica/Gym/Spa) — ahora mencionan Instagram/TikTok/video/CRM/content donde tiene sentido por niche",
      "Healthcare conservador: Clínica Dental NO mete 'Social Content Studio' como benefit (el AI lo entiende)",
    ],
  },
  {
    version: "0.7.8",
    date: "2026-05-18",
    title: "Landing Pages — Celery Worker FK Fix + Generator E2E Verified",
    changes: [
      "CRITICAL: celery worker no podía enriquecer leads con landing_page_id — 'FK leads.landing_page_id could not find table landing_pages'",
      "Fix: scheduled.py importa LandingPage + LandingPageVisit (mismo patrón que Payment) para resolver el mapper",
      "Verificado: lead desde LP → enrichment (score 78.5+) → AI Analysis email enviado → nurture sequence avanzado",
      "E2E test: 4 niches generados con Kimi (Restaurante 16KB, Clínica Dental 16.2KB, Gym 16.0KB, Spa Beverly Hills 16.2KB) con 56 keys completas",
      "Cada niche genera copy distinto y profesional: testimonials, benefits, FAQs adaptados al negocio",
      "Form de captura: first_name, last_name, email, phone, website — verificado en los 4 niches",
      "Lead pipeline confirmado: form submit → /api/v1/leads/public → Lead creado → Celery enrich_and_welcome_lead → email 'Your AI automation analysis for X'",
    ],
  },
  {
    version: "0.7.7",
    date: "2026-05-18",
    title: "Landing Pages — Route Ordering Fix + Compare Enrichment",
    changes: [
      "CRITICAL: tracking pixel /api/v1/landing-pages/track devolvía 401 — analytics siempre mostraban 0 visitas",
      "CRITICAL: /random y /public/active eran inalcanzables (eclipsados por /{landing_page_id})",
      "Fix: reordenadas rutas concretas ANTES del path-param /{landing_page_id} en landing_pages.py",
      "Fix: /compare ahora incluye email_replies y calls_made por landing page (faltaba aggregation)",
      "Fix: workspace_id NULL-safe en activate/create/update (Postgres NULL==NULL devuelve NULL, no TRUE)",
      "Fix: slug uniqueness scoped a workspace (antes era global, bloqueaba slugs idénticos entre workspaces)",
      "Fix: DELETE landing page borra explícitamente landing_page_visits antes (evita FK constraint si no hay CASCADE)",
      "Fix: /random ahora redirige a /lp/{slug} (URL pública SEO-friendly) en vez de /landing?lp=",
    ],
  },
  {
    version: "0.7.6",
    date: "2026-05-18",
    title: "Content Studio — Unified Buffer Snapshot + Rate-limit Banner",
    changes: [
      "Fix: 4 tabs de Content Studio (Publicaciones, Calendario, Analytics, Monitoreo) rotos por Buffer 429",
      "New: /content-api/buffer-snapshot — un solo endpoint con {channels, posts, limits} en una query GraphQL",
      "New: hook useBufferData con caché module-level + pub/sub para compartir datos entre los 4 tabs",
      "New: RateLimitBanner con countdown preciso (lee retry-after header, no window:24h del body)",
      "New: lib/buffer.ts cliente unificado con 5min fresh + 24h stale + rate-limit hint pegajoso",
      "Fix: PostsList filtra client-side (sin re-fetch por filtro)",
      "Fix: PostCalendar sin re-fetch al cambiar mes",
      "Fix: AnalyticsDashboard text-gold inválido reemplazado por text-yellow-300; charts muestran 'Sin datos' elegante",
      "Fix: BufferStatus empty state amigable cuando no hay caché",
      "Fix: PipelineHistory infiere status 'completed' por presencia de scripts[]/produced[] (columna Content ya no muestra '—')",
      "Reduce Buffer API consumption: 5+ calls por dashboard load → 1 call compartida (caché 5min)",
    ],
  },
  {
    version: "0.7.5",
    date: "2026-05-17",
    title: "Content Studio Pipeline — Video Fixes + Login Repair + Buffer Caching",
    changes: [
      "Fix: frontend login container conectado a red Docker correcta (eko-ai-bussinnes-automation_default)",
      "Fix: API caching de 30s en /content-api/posts, /buffer-posts, /limits para evitar rate limit de Buffer",
      "Fix: auto-publisher script lee videos reales del pipeline output (no hardcodeados)",
      "Fix: frontend container mounts output/ y config/ para endpoints locales (pipelines, stats)",
      "Fix: TypeScript build error en api-cache.ts (for...of Map.keys -> Array.from)",
      "Content Studio: 4 escenas por short + 6 por long con múltiples VIDEO_PROMPTs",
      "Content Studio: subtítulos ASS con DejaVu Sans, fondo negro semitransparente, bottom-centered",
      "Content Studio: crossfade transitions xfade 0.8s entre clips",
      "Content Studio: end frame CTA dinámico con nombre, dirección, oferta, precio",
      "Content Studio: Edge-TTS fallback (es-MX-JorgeNeural) para TTS en español",
      "Pipeline: prueba real generó short (29.9s) + long (79.0s) con FLUX + Ken Burns",
    ],
  },
  {
    version: "0.7.4",
    date: "2026-05-13",
    title: "Landing Page Builder v2 — UI + Generation + SEO",
    changes: [
      "Landing Pages: Navbar agregado para navegación completa",
      "Landing Pages: card 'Landing Page en Uso' con preview thumbnail y stats",
      "Landing Pages: card fallback 'Sistema' cuando no hay páginas dinámicas",
      "Landing Pages: botón 'Generate with AI' prominente y siempre visible",
      "Landing Pages: 4 templates de prompt pre-cargados (Restaurante, Clínica, Gym, Spa)",
      "Landing Pages: tabs Pages / Compare con comparación A/B de conversiones",
      "Fix: generación con IA usa modelo del sistema (evita 400 Bad Request por mismatch de proveedor)",
      "Fix: lista se refresca automáticamente tras crear draft desde 'Generate with AI'",
      "Fix: workspace filter backward compatibility para landing pages legacy",
      "SEO: URLs limpias /lp/{slug} vía nginx rewrite para bots y crawlers",
      "Cal.com link dinámico en HTML generado (lee settings de app)",
    ],
  },
  {
    version: "0.7.3",
    date: "2026-05-11",
    title: "Delete Lead Fix + Celery Stability",
    changes: [
      "Fix: botón Eliminar ahora borra leads correctamente (cascade delete de 7 tablas relacionadas)",
      "Fix: frontend muestra alert() cuando delete falla en vez de silenciar el error",
      "Fix: Celery worker RuntimeError 'Event loop is closed' — migrado a prefork pool + engine recreation",
      "Fix: WebsiteAnalyzer 403 bypass — retry sin User-Agent cuando sitio bloquea bots",
      "Fix: feature flags de website (booking, chatbot, etc.) ahora persisten en Lead model",
    ],
  },
  {
    version: "0.7.2",
    date: "2026-05-10",
    title: "Landing Page Hardening + Feature Flags",
    changes: [
      "Landing page envía Free AI Analysis email inmediatamente tras captura de lead",
      "Fix: hero form recargaba página por falta de e.preventDefault()",
      "Fix: schema PublicLeadCreate ahora acepta website, city, state",
      "Fix: auto-reply con caracteres chinos en español — language detection persistido",
      "Emails de bienvenida ahora crean Interaction record con email_status=sent",
      "Website feature flags persistidos: has_booking, has_chatbot, has_ecommerce, etc.",
    ],
  },
  {
    version: "0.7.1",
    date: "2026-05-05",
    title: "Inbox, DNS, Voice Agent y UX",
    changes: [
      "Inbox agrupado por lead con conteo de mensajes y threading de conversaciones",
      "Webhook de correos entrantes con auto-respuesta IA y keywords en inglés/español",
      "Formateo de emails: texto plano a HTML con párrafos y saltos de línea",
      "Pixel de tracking para apertura de correos",
      "Configuración DNS completa: SPF + DKIM + DMARC para biz.ekoaiautomation.com",
      "Soporte para Google Meet en reservas de demo (alternativa a Zoom)",
      "Manejo de zona horaria en links de calendario (America/Denver)",
      "Fix de RLS/workspace: migración de interacciones legacy a workspace default",
      "Botón de versión + modal de historial de cambios en navbar",
      "Creación manual de leads desde /leads (formulario modal con validación)",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-04-28",
    title: "FASE 8: AI Proposal Generator + Email Reply Agent + VAPI Voice Agent",
    changes: [
      "AI Proposal Generator: generación automática de propuestas personalizadas",
      "Email Reply Agent: respuestas automáticas inteligentes a emails entrantes",
      "VAPI Voice Agent: agente de voz con integración VAPI para llamadas",
    ],
  },
  {
    version: "0.6.1",
    date: "2026-04-26",
    title: "Pipeline Hardening + Full Sales Cycle Demo",
    changes: [
      "Pipeline fix: valid transitions, interaction tracking, score-0 hardening",
      "Full sales cycle demo features",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-04-25",
    title: "Enrichment Pipeline Hardening",
    changes: [
      "Enrichment pipeline hardening y mejoras de estabilidad",
      "Client-side sort fix + autocomplete + deploy hardening",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-04-24",
    title: "Booking System + Cal.com Integration",
    changes: [
      "Sistema de reservas de citas integrado",
      "Integración con Cal.com para scheduling",
      "Webhooks de calendario y recordatorios",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-04-24",
    title: "JWT Auth + Protected Routes + Multi-tenancy",
    changes: [
      "Sistema de autenticación JWT",
      "Rutas protegidas en frontend",
      "Multi-tenancy con workspaces",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-04-24",
    title: "Email Sequences + Celery + CRM Automation",
    changes: [
      "Secuencias de emails automatizadas",
      "Tareas en background con Celery + Redis",
      "Automatización de CRM",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-04-24",
    title: "Outreach + CRM Pipeline Completo",
    changes: [
      "Pipeline completo de outreach",
      "CRM con gestión de leads y deals",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-04-23",
    title: "MVP Scaffolding — Discovery, Research, Outreach, Dashboard",
    changes: [
      "Discovery: búsqueda de negocios en Google Maps, Yelp, LinkedIn",
      "Research: enriquecimiento de leads con IA",
      "Outreach: envío de emails personalizados",
      "Dashboard: panel de control con métricas",
      "Integración con Paperclip AI",
    ],
  },
];
